# Core Colors
background            #121318
foreground            #e2e2e9
selection_foreground  #b0c6ff
selection_background  #142e60
cursor                #b0c6ff
cursor_text_color     #121318

# Regular Colors
color0  #121318
color1  #ffb4ab
color2  #b0c6ff
color3  #e0bbde
color4  #d9e2ff
color5  #dce2f9
color6  #c0c6dc
color7  #e2e2e9

# Bright Colors
color8  #38393f
color9  #ffb4ab
color10 #b0c6ff
color11 #e0bbde
color12 #d9e2ff
color13 #dce2f9 
color14 #c0c6dc
color15 #e2e2e9