# Core Colors
background            #18130b
foreground            #ede1d4
selection_foreground  #f2be6e
selection_background  #442c00
cursor                #f2be6e
cursor_text_color     #18130b

# Regular Colors
color0  #18130b
color1  #ffb4ab
color2  #f2be6e
color3  #b6cea3
color4  #ffddaf
color5  #f9dfbb
color6  #dcc3a1
color7  #ede1d4

# Bright Colors
color8  #3f382f
color9  #ffb4ab
color10 #f2be6e
color11 #b6cea3
color12 #ffddaf
color13 #f9dfbb 
color14 #dcc3a1
color15 #ede1d4