[config]

[templates.hyprland]
input_path = '~/.config/matugen/templates/colors.lua' # Match your actual template filename
output_path = '~/.config/hypr/colors.lua'             # Put it directly in the hypr folder so require("colors") works
post_hook = 'hyprctl reload'

[templates.wlogout]
input_path = '~/.config/matugen/templates/wlogout.css'
output_path = '~/.config/wlogout/style.css'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.cava]
input_path = '~/.config/matugen/templates/cava'
output_path = '~/.config/cava/config'
post_hook = 'pkill -USR1 cava'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/colors.rasi'


[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = '~/.config/hypr/scripts/reload-gtk.sh'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = '~/.config/hypr/scripts/reload-gtk.sh'

[templates.kvantum]
input_path = '~/.config/matugen/templates/kvantum.kvconfig'
output_path = '~/.config/Kvantum/Matugen/Matugen.kvconfig'

[templates.qt5]
input_path = '~/.config/matugen/templates/qt_colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6]
input_path = '~/.config/matugen/templates/qt_colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.pywal]
input_path = '~/.config/matugen/templates/pywal.json'
output_path = '~/.cache/wal/colors.json'
post_hook = '/home/arefin/.local/bin/pywalfox update'

[templates.swaync]
input_path = '~/.config/matugen/templates/swaync.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.waybar]
input_path = '~/.config/matugen/templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar && ~/.config/hypr/scripts/refresh.sh'