#!/bin/bash

# 1. Format input: keep text searchable but display only the emoji icon
selected=$(sed '1,/^#  DATA #$/d' "$0" | awk '{print $0 "\0display\x1f" $1}' | rofi -dmenu -p "emoji" -theme-str 'listview { columns: 5; lines: 10; fixed-columns: true; } element-text { horizontal-align: 0.0; font: "JetBrainsMono Nerd Font 17"; }' | cut -d ' ' -f 1)

# 2. If an emoji was selected, copy and paste it
if [ -n "$selected" ]; then
    echo -n "$selected" | wl-copy
    # Simulate pressing Ctrl+Shift+V or Ctrl+V to paste into the active window
    sleep 0.1
    wtype -M ctrl -M shift -k v -m shift -m ctrl
    # Alternatively, if wtype doesn't work for you, use ydotool or wlr-randr equivalents:
    # ydotool key 29:1 42:1 47:1 47:0 42:0 29:0
fi

exit

#  DATA #
😀 Grinning Face (happy|smile|joy|grin|cheerful)
😃 Grinning Face with Big Eyes (laugh|smile|eyes|happy|yay)
😄 Grinning Face with Smiling Eyes (laugh|smile|joy|happy|haha)
😁 Beaming Face with Smiling Eyes (smile|grin|teeth|cheese|happy)
😆 Grinning Squinting Face (lol|laugh|haha|xd|squint)
😅 Grinning Face with Sweat (sweat|smile|relief|nervous|whew)
🤣 Rolling on the Floor Laughing (rofl|lmao|laugh|tears|dying)
😂 Face with Tears of Joy (cry|laugh|joy|tears|lol|lmao)
🙂 Slightly Smiling Face (smile|fine|okay|subtle|thisisfine)
🙃 Upside-Down Face (silly|sarcasm|irony|joke|upside)
🫠 Melting Face (melt|heat|sarcasm|dread|disappear)
😉 Winking Face (wink|eye|flirt|joke|kidding)
😊 Smiling Face with Smiling Eyes (shy|blush|cute|warm|happy)
😇 Smiling Face with Halo (angel|halo|innocent|good|pure)
🥰 Smiling Face with Hearts (love|crush|adore|affection|cute)
😍 Smiling Face with Heart-Eyes (love|crush|eyes|heart|obsessed)
🤩 Star-Struck (star|shocked|wow|amaze|excited)
😘 Face Blowing a Kiss (love|kiss|mwah|affection|blow)
😗 Kissing Face (kiss|puckered|whistle|smooch)
☺️ Smiling Face (blush|happy|warm|content)
😚 Kissing Face with Closed Eyes (kiss|blush|cute|affection)
😙 Kissing Face with Smiling Eyes (kiss|whistle|happy|smooch)
🥲 Smiling Face with Tear (tear|sadsmile|cry|brave|pain)
😋 Face Savoring Food (yummy|food|delicious|hungry|tongue)
😛 Face with Tongue (prank|tongue|silly|joke|blep)
😜 Winking Face with Tongue (wink|prank|joke|crazy|silly)
🤪 Zany Face (crazy|goofy|wild|wacky|silly)
😝 Squinting Face with Tongue (prank|xd|tongue|laugh|joke)
🤑 Money-Mouth Face (money|rich|cash|dollar|wealth)
🤗 Hugging Face (hug|hands|care|embrace|support)
🤭 Face with Hand Over Mouth (oops|giggle|secret|shock|shy)
🫢 Face with Open Eyes and Hand Over Mouth (shock|gasp|omg|surprise)
🫣 Face with Peeking Eye (peek|hide|scared|cringe|look)
🤫 Shushing Face (quiet|shh|secret|silence|mute)
🤔 Thinking Face (hmmm|think|wonder|ponder|confused)
🫡 Saluting Face (salute|respect|yes|sir|army)
🤐 Zipper-Mouth Face (secret|zip|quiet|silence|hush)
🤨 Face with Raised Eyebrow (skeptical|sus|rock|doubt|suspicious)
😐 Neutral Face (meh|blank|bored|indifferent)
😑 Expressionless Face (blank|done|annoyed|bruh|flat)
😶 Face Without Mouth (silent|speechless|quiet|blank)
🫥 Dotted Line Face (hide|invisible|depression|fade|clouds)
😏 Smirking Face (smug|flirt|suggestive|sly)
😒 Unamused Face (bored|annoyed|done|displeased|meh)
🙄 Face with Rolling Eyes (eyeroll|annoyed|whatever|sigh)
😬 Grimacing Face (awkward|yikes|cringe|nervous|teeth)
🤥 Lying Face (pinocchio|liar|lie|false|nose)
😌 Relieved Face (relaxed|phew|calm|peace)
😔 Pensive Face (sad|sorry|depressed|down|thinking)
😪 Sleepy Face (nap|tired|drool|sleep)
🤤 Drooling Face (drool|hungry|yummy|sleep)
😴 Sleeping Face (zzz|sleep|tired|bed|snore)
😷 Face with Medical Mask (sick|mask|covid|ill|doctor)
🤒 Face with Thermometer (fever|sick|temperature|ill|hot)
🤕 Face with Head-Bandage (hurt|injury|ouch|pain|bandage)
🤢 Nauseated Face (vomit|sick|gross|disgust|green)
🤮 Face Vomiting (puke|throwup|gross|sick|barf)
🤧 Sneezing Face (allergy|sick|sneeze|achoo|cold)
🥵 Hot Face (sweating|heat|spicy|summer|thirsty)
🥶 Cold Face (freezing|cold|ice|winter|frost)
🥴 Woozy Face (tipsy|drunk|dizzy|confused|wavy)
😵 Dizzy Face (spent|dead|spiral|dizzy|shocked)
😵‍💫 Face with Spiral Eyes (hypnotized|dizzy|confused|woah)
🤯 Exploding Head (shock|mindblown|boom|wow|crazy)
🤠 Cowboy Hat Face (cowboy|yeehaw|country|hat)
🥳 Partying Face (celebration|party|birthday|yay|horn)
🥸 Disguised Face (disguise|spy|glasses|mustache|fake)
😎 Smiling Face with Sunglasses (cool|swag|glasses|sun|boss)
🤓 Nerd Face (geek|nerd|smart|glasses|dork)
🧐 Face with Monocle (fancy|classy|detective|hmm|investigate)
😕 Confused Face (huh|what|confused|unsure)
😟 Worried Face (nervous|scared|anxious|sad)
🙁 Slightly Frowning Face (sad|frown|disappointed)
☹️ Frowning Face (upset|sad|mad|frown)
😮 Face with Open Mouth (wow|surprise|omg|gasp)
😯 Hushed Face (quiet|surprise|wow|speechless)
😲 Astonished Face (shocked|wow|omg|surprised)
😳 Flushed Face (blush|embarrassed|shy|omg|shock)
🥺 Pleading Face (begging|bottom|cute|eyes|puppy)
🥹 Face Holding Back Tears (proud|cry|happytears|emotional)
😦 Frowning Face with Open Mouth (huh|shock|sad)
😧 Anguished Face (shocked|pain|scared)
😨 Fearful Face (scared|fear|shock|terrified)
😰 Anxious Face with Sweat (nervous|stress|worry|sweat)
😥 Sad but Relieved Face (phew|sweat|relief|worry)
😢 Crying Face (tears|sad|cry|upset)
😭 Loudly Crying Face (cry|sob|bawl|sad|tears)
😱 Face Screaming in Fear (panic|scream|fear|scary|horror)
😖 Confounded Face (confused|frustrated|sick|pain)
😣 Persevering Face (struggle|push|pain|trying)
😞 Disappointed Face (sad|fail|sigh|letdown)
😓 Downcast Face with Sweat (tired|sweat|stress|hardwork)
😩 Weary Face (upset|exhausted|done|tired)
😫 Tired Face (whine|exhausted|sleepy|done)
🥱 Yawning Face (sleepy|tired|yawn|bored)
😤 Face with Steam From Nose (mad|proud|steam|angry|frustrated)
😡 Pouting Face (angry|mad|red|rage|furious)
😠 Angry Face (mad|angry|upset|grr)
🤬 Face with Symbols on Mouth (cursing|swearing|mad|angry|censor)
🙂‍↔️ Head Shaking Horizontally (no|shake|nah|disagree|faceee|uhu)
🙂‍↕️ Head Shaking Vertically (yes|nod|agree|mogger|facee)
🫨 Shaking Face (omg|shook|earthquake|vibrate|gahhh)
🫩 Sleepy Face Pro (sleep|pro|tired|custom)
🫪 Distorted Face (distorted|weird|custom|melt)
😈 Smiling Face with Horns (devil|evil|naughty|bad|smile)
👿 Angry Face with Horns (devil|angry|demon|mad|rage)
💀 Skull (dead|death|skeleton|rip|imdead)
☠️ Skull and Crossbones (poison|danger|dead|pirate)
💩 Pile of Poo (poop|crap|bs|turd|funny)
🤡 Clown Face (clown|fool|joke|circus)
👹 Ogre (demon|monster|scary|oni)
👺 Goblin (monster|tengu|scary|red)
👻 Ghost (spooky|boo|halloween|snapchat)
👽 Alien (ufo|space|et|martian)
👾 Alien Monster (game|retro|space|invader)
🤖 Robot (bot|ai|tech|machine)
😺 Grinning Cat Face (happy|cat|smile|meow)
😸 Grinning Cat with Smiling Eyes (laugh|cat|smile)
😹 Cat with Tears of Joy (rofl|laugh|cat|tears|cry)
😻 Smiling Cat with Heart-Eyes (love|cat|crush|eyes)
😼 Cat with Wry Smile (smug|cat|sly|smirk)
😽 Kissing Cat (kiss|cat|smooch|love)
🙀 Weary Cat (shocked|cat|omg|scared)
😿 Crying Cat (sad|cat|cry|tears)
😾 Pouting Cat (angry|cat|mad|grumpy)
🙈 See-No-Evil Monkey (hide|monkey|blind|cringe)
🙉 Hear-No-Evil Monkey (deaf|monkey|ignore|ears)
🙊 Speak-No-Evil Monkey (silent|monkey|secret|oops)
💋 Kiss Mark (kiss|lips|lipstick|makeup|love)
💌 Love Letter (love|letter|envelope|mail|valentine)
💘 Heart with Arrow (heart|arrow|cupid|love|romance)
💝 Heart with Ribbon (heart|ribbon|gift|box|love)
💖 Sparkling Heart (sparkle|heart|love|shiny|magic)
💗 Growing Heart (growing|heart|affection|pulse|love)
💓 Beating Heart (beating|heart|pulse|love|alarm)
💞 Revolving Hearts (revolving|hearts|love|spin|two)
💕 Two Hearts (two|hearts|pair|love|affection)
💟 Heart Decoration (heart|decoration|square|purple|love)
❣️ Heart Exclamation (heart|exclamation|love|punctuation|red)
💔 Broken Heart (broken|heart|heartbreak|sad|split)
❤️ Red Heart (red|heart|love|passion|classic)
🧡 Orange Heart (orange|heart|affection|warm)
💛 Yellow Heart (yellow|heart|affection|friendship)
💚 Green Heart (green|heart|affection|nature|jealous)
💙 Blue Heart (blue|heart|affection|cold|sad)
💜 Purple Heart (purple|heart|affection|royal)
🤎 Brown Heart (brown|heart|coffee|chocolate|earth)
🖤 Black Heart (black|heart|evil|dark|goth)
🤍 White Heart (white|heart|pure|clean|peace)
💯 Hundred Points (100|hundred|points|score|perfect|keepit100)
💢 Anger Symbol (anger|symbol|mad|vein|comic)
💥 Collision (collision|explosion|boom|bang|comic)
💫 Dizzy (dizzy|star|magic|sparkle|shoot)
💦 Sweat Droplets (sweat|droplets|splash|water|wet)
💨 Dashing Away (dashing|fast|wind|smoke|run)
🕳️ Hole (hole|pit|embarrassing|dark|fall)
💣 Bomb (bomb|explosion|boom|blast|boom)
💬 Speech Bubble (speech|bubble|message|talk|chat)
👁️‍🗨️ Eye in Speech Bubble (eye|speech|info|witness)
🗨️ Left Speech Bubble (left|bubble|message|talk|chat)
🗯️ Right Anger Bubble (anger|bubble|shout|mad|yell)
💭 Thought Bubble (thought|bubble|dream|think|cloud)
💤 Zzz (zzz|sleeping|dream|snore|tired)
👋 Waving Hand (wave|hand|hello|hi|goodbye|bye)
🤚 Raised Back of Hand (raised|backhand|stop|highfive|slap)
🖐️ Hand with Fingers Splayed (splayed|hand|palm|five|stop)
✋ Raised Hand (raised|hand|stop|highfive|halt)
🖖 Vulcan Salute (vulcan|salute|spock|startrek|prosper)
👌 OK Hand (ok|hand|perfect|good|gotit)
🤏 Pinching Hand (pinching|hand|small|tiny|little)
✌️ Victory Hand (victory|hand|peace|two|v)
🤞 Crossed Fingers (crossed|fingers|lucky|hope|promise)
🤟 Love-You Gesture (love|gesture|hand|sign|ily)
🤘 Sign of the Horns (horns|sign|rock|metal|roll)
🤙 Call Me Hand (call|me|shaka|surf|phone)
👈 Backhand Index Pointing Left (index|pointing|left|look|here)
👉 Backhand Index Pointing Right (index|pointing|right|look|there)
👆 Backhand Index Pointing Up (index|pointing|up|look|above)
🖕 Middle Finger (middle|finger|rude|flip|bird)
👇 Backhand Index Pointing Down (index|pointing|down|look|below)
☝️ Index Pointing Up (index|pointing|up|wait|numberone)
👍 Thumbs Up (thumbs|up|agree|yes|good|like)
👎 Thumbs Down (thumbs|down|dislike|no|bad)
✊ Raised Fist (raised|fist|power|solidarity|bump)
👊 Oncoming Fist (oncoming|fist|punch|brofist|bump)
🤛 Left-Facing Fist (left|fist|bump|punch)
🤜 Right-Facing Fist (right|fist|bump|punch)
👏 Clapping Hands (clapping|hands|applause|bravo|yay)
🙌 Raising Hands (raising|hands|hooray|celebration|praise)
👐 Open Hands (open|hands|cupped|hug|jazz)
🤲 Palms Up Together (palms|up|prayer|beg|dua)
🤝 Handshake (handshake|agreement|deal|meeting|shake)
🙏 Folded Hands (folded|hands|pray|please|thanks|namaste)
✍️ Writing Hand (writing|hand|compose|pen|write)
💅 Nail Polish (nail|polish|beauty|sass|care)
🤳 Selfie (selfie|camera|phone|photo|arm)
💪 Flexed Biceps (flexed|biceps|strong|muscle|workout)
🦾 Mechanical Arm (mechanical|arm|tech|cyborg|prosthetic)
🦿 Mechanical Leg (mechanical|leg|tech|cyborg|prosthetic)
🦵 Leg (leg|kick|limb|foot)
🦶 Foot (foot|stomp|kick|barefoot)
👂 Ear (ear|listening|sound|hear)
🦻 Ear with Hearing Aid (hearing|aid|access|deaf|listen)
👃 Nose (nose|smell|sniff|scent)
🧠 Brain (brain|smart|genius|mind|think)
🦷 Tooth (tooth|dentist|teeth|bite)
🦴 Bone (bone|skeleton|dog|halloween)
👀 Eyes (eyes|watching|peek|look|stare)
👁️ Eye (eye|looking|see|stare|vision)
👅 Tongue (tongue|mouth|playful|lick|taste)
👄 Mouth (mouth|lips|kiss|speak)
👶 Baby (baby|child|toddler|infant)
🧒 Child (child|young|kid|toddler)
👦 Boy (boy|male|teenager|kid)
👧 Girl (girl|female|teenager|kid)
🧑 Person (person|human|neutral|adult)
👱 Person: Blond Hair (blond|person|hair|blonde)
👨 Man (man|male|guy|adult)
🧔 Person: Beard (bearded|man|guy|beard)
👨‍🦰 Man: Red Hair (red|hair|man|ginger)
👨‍🦱 Man: Curly Hair (curly|hair|man)
👨‍🦳 Man: White Hair (white|hair|man|gray)
👨‍🦲 Man: Bald (bald|man|guy|hairless)
👩 Woman (woman|female|lady|adult)
👩‍🦰 Woman: Red Hair (red|hair|woman|ginger)
🧑‍🦰 Person: Red Hair (red|hair|person|ginger)
👩‍🦱 Woman: Curly Hair (curly|hair|woman)
🧑‍🦱 Person: Curly Hair (curly|hair|person)
👩‍🦳 Woman: White Hair (white|hair|woman|gray)
🧑‍🦳 Person: White Hair (white|hair|person|gray)
👩‍🦲 Woman: Bald (bald|woman|lady|hairless)
🧑‍🦲 Person: Bald (bald|person|neutral|hairless)
👱‍♀️ Woman: Blond Hair (blond|woman|girl|blonde)
👱‍♂️ Man: Blond Hair (blond|man|guy|blonde)
🧓 Older Person (older|person|senior|elder)
👴 Old Man (old|man|senior|elder|grandpa)
👵 Old Woman (old|woman|senior|elder|grandma)
🙍 Person Frowning (frowning|person|sad|upset)
🙍‍♂️ Man Frowning (frowning|man|sad|upset)
🙍‍♀️ Woman Frowning (frowning|woman|sad|upset)
🙎 Person Pouting (pouting|person|upset|mad)
🙎‍♂️ Man Pouting (pouting|man|upset|mad)
🙎‍♀️ Woman Pouting (pouting|woman|upset|mad)
🙅 Person Gesturing No (gesturing|no|decline|stop|x)
🙅‍♂️ Man Gesturing No (man|gesturing|no|decline|stop)
🙅‍♀️ Woman Gesturing No (woman|gesturing|no|decline|stop)
🙆 Person Gesturing OK (gesturing|ok|agree|yes|halo)
🙆‍♂️ Man Gesturing OK (man|gesturing|ok|agree|yes)
🙆‍♀️ Woman Gesturing OK (woman|gesturing|ok|agree|yes)
💁 Person Tipping Hand (tipping|hand|info|sassy|help)
💁‍♂️ Man Tipping Hand (man|tipping|info|sassy|help)
💁‍♀️ Woman Tipping Hand (woman|tipping|info|sassy|help)
🙋 Person Raising Hand (raising|hand|question|pickme)
🙋‍♂️ Man Raising Hand (man|raising|hand|question|pickme)
🙋‍♀️ Woman Raising Hand (woman|raising|hand|question|pickme)
🧏 Deaf Person (deaf|person|access|hear|sign)
🧏‍♂️ Deaf Man (deaf|man|access|hear|sign)
🧏‍♀️ Deaf Woman (deaf|woman|access|hear|sign)
🙇 Person Bowing (bowing|person|respect|sorry|apology)
🙇‍♂️ Man Bowing (man|bowing|respect|sorry|apology)
🙇‍♀️ Woman Bowing (woman|bowing|respect|sorry|apology)
🤦 Person Facepalming (facepalm|disappointed|smh|sigh)
🤦‍♂️ Man Facepalming (man|facepalm|disbelief|smh|sigh)
🤦‍♀️ Woman Facepalming (woman|facepalm|disbelief|smh|sigh)
🤷 Person Shrugging (shrugging|person|doubt|idk|whatever)
🤷‍♂️ Man Shrugging (man|shrugging|doubt|idk|whatever)
🤷‍♀️ Woman Shrugging (woman|shrugging|doubt|idk|whatever)
🧑‍⚕️ Health Worker (health|worker|doctor|nurse|medic)
👨‍⚕️ Man Health Worker (man|doctor|nurse|medic)
👩‍⚕️ Woman Health Worker (woman|doctor|nurse|medic)
🧑‍🎓 Student (student|graduate|learn|school|university)
👨‍🎓 Man Student (man|student|graduate|school)
👩‍🎓 Woman Student (woman|student|graduate|school)
🧑‍🏫 Teacher (teacher|instructor|professor|school)
👨‍🏫 Man Teacher (man|teacher|professor|school)
👩‍🏫 Woman Teacher (woman|teacher|professor|school)
🧑‍⚖️ Judge (judge|law|court|justice)
👨‍⚖️ Man Judge (man|judge|court|justice)
👩‍⚖️ Woman Judge (woman|judge|court|justice)
🧑‍🌾 Farmer (farmer|crops|rancher|agriculture)
👨‍🌾 Man Farmer (man|farmer|rancher|agriculture)
👩‍🌾 Woman Farmer (woman|farmer|rancher|agriculture)
🧑‍🍳 Cook (cook|chef|kitchen|food)
👨‍🍳 Man Cook (man|cook|chef|kitchen)
👩‍🍳 Woman Cook (woman|cook|chef|kitchen)
🧑‍🔧 Mechanic (mechanic|plumber|technician|fix)
👨‍🔧 Man Mechanic (man|mechanic|plumber|fix)
👩‍🔧 Woman Mechanic (woman|mechanic|plumber|fix)
🧑‍🏭 Factory Worker (factory|worker|labor|industry)
👨‍🏭 Man Factory Worker (man|factory|worker|labor)
👩‍🏭 Woman Factory Worker (woman|factory|worker|labor)
🧑‍💼 Office Worker (office|worker|manager|business)
👨‍💼 Man Office Worker (man|office|worker|business)
👩‍💼 Woman Office Worker (woman|office|worker|business)
🧑‍🔬 Scientist (scientist|chemist|engineer|research)
👨‍🔬 Man Scientist (man|scientist|chemist|research)
👩‍🔬 Woman Scientist (woman|scientist|chemist|research)
🧑‍💻 Technologist (technologist|coder|developer|programmer|hacker)
👨‍💻 Man Technologist (man|coder|programmer|hacker)
👩‍💻 Woman Technologist (woman|coder|programmer|hacker)
🧑‍🎤 Singer (singer|artist|rockstar|music)
👨‍🎤 Man Singer (man|singer|rockstar|music)
👩‍🎤 Woman Singer (woman|singer|rockstar|music)
🧑‍🎨 Artist (artist|painter|draw|palette)
👨‍🎨 Man Artist (man|artist|painter|draw)
👩‍🎨 Woman Artist (woman|artist|painter|draw)
🧑‍✈️ Pilot (pilot|aviator|fly|plane)
👨‍✈️ Man Pilot (man|pilot|aviator|plane)
👩‍✈️ Woman Pilot (woman|pilot|aviator|plane)
🧑‍🚀 Astronaut (astronaut|space|rocket|nasa)
👨‍🚀 Man Astronaut (man|astronaut|rocket|space)
👩‍🚀 Woman Astronaut (woman|astronaut|rocket|space)
🧑‍🚒 Firefighter (firefighter|fireman|fire|rescue)
👨‍🚒 Man Firefighter (man|firefighter|fireman|rescue)
👩‍🚒 Woman Firefighter (woman|firefighter|fireman|rescue)
👮 Police Officer (police|officer|cop|law)
👮‍♂️ Man Police Officer (man|police|cop|law)
👮‍♀️ Woman Police Officer (woman|police|cop|law)
🕵️ Detective (detective|spy|crime|investigate)
🕵️‍♂️ Man Detective (man|detective|spy|investigate)
🕵️‍♀️ Woman Detective (woman|detective|spy|investigate)
💂 Guard (guard|protect|royal|security)
💂‍♂️ Man Guard (man|guard|royal|security)
💂‍♀️ Woman Guard (woman|guard|royal|security)
👷 Construction Worker (construction|worker|builder|hardhat)
👷‍♂️ Man Construction Worker (man|builder|worker|hardhat)
👷‍♀️ Woman Construction Worker (woman|builder|worker|hardhat)
🤴 Prince (prince|royal|king|crown)
👸 Princess (princess|royal|queen|crown)
👳 Person Wearing Turban (turban|person|headdress)
👳‍♂️ Man Wearing Turban (man|wearing|turban|headdress)
👳‍♀️ Woman Wearing Turban (woman|wearing|turban|headdress)
👲 Man With Skullcap (skullcap|man|chinese|hat)
🧕 Woman with Headscarf (headscarf|woman|hijab|muslim)
🤵 Person in Tuxedo (tuxedo|man|groom|suit|formal)
👰 Person with Veil (bride|veil|wedding|marriage)
🤰 Pregnant Woman (pregnant|woman|baby|mother)
🤱 Breastfeeding (breastfeeding|nursing|baby|mother)
👼 Baby Angel (baby|angel|halo|cherub)
🎅 Santa Claus (santa|claus|xmas|christmas)
🤶 Mrs. Claus (mrs|claus|xmas|christmas|santa)
🦸 Superhero (superhero|hero|marvel|comic)
🦸‍♂️ Man Superhero (man|superhero|hero|comic)
🦸‍♀️ Woman Superhero (woman|superhero|heroine|comic)
🦹 Supervillain (supervillain|evil|bad|villain|comic)
🦹‍♂️ Man Supervillain (man|supervillain|villain|evil)
🦹‍♀️ Woman Supervillain (woman|supervillain|villain|evil)
🧙 Mage (mage|sorcerer|magic|wizard)
🧙‍♂️ Man Mage (man|mage|sorcerer|wizard)
🧙‍♀️ Woman Mage (woman|mage|witch|wizard)
🧚 Fairy (fairy|magical|wings|sprite)
🧚‍♂️ Man Fairy (man|fairy|male|wings)
🧚‍♀️ Woman Fairy (woman|fairy|female|wings)
🧛 Vampire (vampire|dracula|blood|bite)
🧛‍♂️ Man Vampire (man|vampire|dracula|blood)
🧛‍♀️ Woman Vampire (woman|vampire|dracula|blood)
🧜 Merperson (merperson|sea|triton|ocean)
🧜‍♂️ Merman (merman|sea|triton|ocean)
🧜‍♀️ Mermaid (mermaid|sea|woman|ocean)
🧝 Elf (elf|magical|fantasy|lotr)
🧝‍♂️ Man Elf (man|elf|male|fantasy)
🧝‍♀️ Woman Elf (woman|elf|female|fantasy)
🧞 Genie (genie|magical|wishes|lamp)
🧞‍♂️ Man Genie (man|genie|male|lamp)
🧞‍♀️ Woman Genie (woman|genie|female|lamp)
🧟 Zombie (zombie|undead|dead|monster)
🧟‍♂️ Man Zombie (man|zombie|undead|dead)
🧟‍♀️ Woman Zombie (woman|zombie|undead|dead)
💆 Person Getting Massage (massage|spa|relax|head)
💆‍♂️ Man Getting Massage (man|massage|spa|relax)
💆‍♀️ Woman Getting Massage (woman|massage|spa|relax)
💇 Person Getting Haircut (haircut|salon|barber|beauty)
💇‍♂️ Man Getting Haircut (man|haircut|salon|barber)
💇‍♀️ Woman Getting Haircut (woman|haircut|salon|barber)
🚶 Person Walking (walking|move|steps|pedestrian)
🚶‍♂️ Man Walking (man|walking|steps|pedestrian)
🚶‍♀️ Woman Walking (woman|walking|steps|pedestrian)
🧍 Person Standing (standing|still|wait|upright)
🧍‍♂️ Man Standing (man|standing|still|wait)
🧍‍♀️ Woman Standing (woman|standing|still|wait)
🧎 Person Kneeling (kneeling|pray|kneel|down)
🧎‍♂️ Man Kneeling (man|kneeling|pray|down)
🧎‍♀️ Woman Kneeling (woman|kneeling|pray|down)
🧑‍🦯 Person with White Cane (cane|blind|walking|access)
👨‍🦯 Man with White Cane (man|cane|blind|access)
👩‍🦯 Woman with White Cane (woman|cane|blind|access)
🧑‍🦼 Person in Motorized Wheelchair (motorized|wheelchair|access|mobility)
👨‍🦼 Man in Motorized Wheelchair (man|motorized|wheelchair|access)
👩‍🦼 Woman in Motorized Wheelchair (woman|motorized|wheelchair|access)
🧑‍🦽 Person in Manual Wheelchair (manual|wheelchair|access|mobility)
👨‍🦽 Man in Manual Wheelchair (man|manual|wheelchair|access)
👩‍🦽 Woman in Manual Wheelchair (woman|manual|wheelchair|access)
🏃 Person Running (running|race|sprint|jog)
🏃‍♂️ Man Running (man|running|race|sprint)
🏃‍♀️ Woman Running (woman|running|race|sprint)
💃 Woman Dancing (woman|dancing|fun|salsa|party)
🕺 Man Dancing (man|dancing|dancer|disco|party)
🕴️ Person in Suit Levitating (levitating|suit|hover|magic)
👯 People with Bunny Ears (bunny|ears|dancers|party|twins)
👯‍♂️ Men with Bunny Ears (men|bunny|ears|dancers|twins)
👯‍♀️ Women with Bunny Ears (women|bunny|ears|dancers|twins)
🧖 Person in Steamy Room (steamy|room|sauna|sweat|spa)
🧖‍♂️ Man in Steamy Room (man|steamy|sauna|sweat|spa)
🧖‍♀️ Woman in Steamy Room (woman|steamy|sauna|sweat|spa)
🧗 Person Climbing (climbing|rock|boulder|sport)
🧗‍♂️ Man Climbing (man|climbing|rock|boulder)
🧗‍♀️ Woman Climbing (woman|climbing|rock|boulder)
🤺 Person Fencing (fencing|sword|sport|fight)
🏇 Horse Racing (horse|racing|betting|jockey)
⛷️ Skier (skier|winter|snow|sport|ski)
🏂 Snowboarder (snowboarder|winter|snow|sport)
🏌️ Person Golfing (golfing|sport|swing|club)
🏌️‍♂️ Man Golfing (man|golfing|sport|swing)
🏌️‍♀️ Woman Golfing (woman|golfing|sport|swing)
🏄 Person Surfing (surfing|sea|ocean|waves)
🏄‍♂️ Man Surfing (man|surfing|ocean|waves)
🏄‍♀️ Woman Surfing (woman|surfing|ocean|waves)
🚣 Person Rowing Boat (rowing|boat|water|sport)
🚣‍♂️ Man Rowing Boat (man|rowing|boat|water)
🚣‍♀️ Woman Rowing Boat (woman|rowing|boat|water)
🏊 Person Swimming (swimming|pool|water|sport)
🏊‍♂️ Man Swimming (man|swimming|athlete|water)
🏊‍♀️ Woman Swimming (woman|swimming|athlete|water)
⛹️ Person Bouncing Ball (bouncing|ball|sports|basketball)
⛹️‍♂️ Man Bouncing Ball (man|bouncing|ball|basketball)
⛹️‍♀️ Woman Bouncing Ball (woman|bouncing|ball|basketball)
🏋️ Person Lifting Weights (lifting|weights|training|gym)
🏋️‍♂️ Man Lifting Weights (man|lifting|weights|gym)
🏋️‍♀️ Woman Lifting Weights (woman|lifting|weights|gym)
🚴 Person Biking (biking|exercise|bicycle|bike)
🚴‍♂️ Man Biking (man|biking|exercise|bike)
🚴‍♀️ Woman Biking (woman|biking|exercise|bike)
🚵 Person Mountain Biking (mountain|biking|sport|bike)
🚵‍♂️ Man Mountain Biking (man|mountain|biking|sport)
🚵‍♀️ Woman Mountain Biking (woman|mountain|biking|sport)
🤸 Person Cartwheeling (cartwheeling|gymnastics|flip|sport)
🤸‍♂️ Man Cartwheeling (man|cartwheeling|gymnastics|flip)
🤸‍♀️ Woman Cartwheeling (woman|cartwheeling|gymnastics|flip)
🤼 People Wrestling (people|wrestling|sport|fight)
🤼‍♂️ Men Wrestling (men|wrestling|sport|fight)
🤼‍♀️ Women Wrestling (women|wrestling|sport|fight)
🤽 Person Playing Water Polo (water|polo|sports|pool)
🤽‍♂️ Man Playing Water Polo (man|water|polo|pool)
🤽‍♀️ Woman Playing Water Polo (woman|water|polo|pool)
🤾 Person Playing Handball (playing|handball|sport|ball)
🤾‍♂️ Man Playing Handball (man|playing|handball|sport)
🤾‍♀️ Woman Playing Handball (woman|playing|handball|sport)
🤹 Person Juggling (juggling|balance|circus|balls)
🤹‍♂️ Man Juggling (man|juggling|balance|circus)
🤹‍♀️ Woman Juggling (woman|juggling|balance|circus)
🧘 Person in Lotus Position (lotus|position|yoga|zen|meditate)
🧘‍♂️ Man in Lotus Position (man|yoga|zen|meditate)
🧘‍♀️ Woman in Lotus Position (woman|yoga|zen|meditate)
🛀 Person Taking Bath (taking|bath|tub|wash|clean)
🛌 Person in Bed (person|bed|sleep|rest|hotel)
🧑‍🤝‍🧑 People Holding Hands (holding|hands|friends|couple|together)
👭 Women Holding Hands (women|holding|hands|friends|couple)
👫 Woman and Man Holding Hands (woman|man|hands|couple|friends)
👬 Men Holding Hands (men|holding|hands|friends|couple)
💏 Kiss (kiss|couple|dating|romance)
👩‍❤️‍💋‍👨 Kiss: Woman, Man (kiss|woman|man|couple|romance)
👨‍❤️‍💋‍👨 Kiss: Man, Man (kiss|man|man|couple|romance)
👩‍❤️‍💋‍👩 Kiss: Woman, Woman (kiss|woman|woman|couple|romance)
💑 Couple with Heart (couple|heart|love|romance)
👩‍❤️‍👨 Couple with Heart: Woman, Man (couple|heart|woman|man|love)
👨‍❤️‍👨 Couple with Heart: Man, Man (couple|heart|man|love)
👩‍❤️‍👩 Couple with Heart: Woman, Woman (couple|heart|woman|love)
👪 Family (family|parents|child|kids)
👨‍👩‍👦 Family: Man, Woman, Boy (family|man|woman|boy|child)
👨‍👩‍👧 Family: Man, Woman, Girl (family|man|woman|girl|child)
👨‍👩‍👧‍👦 Family: Man, Woman, Girl, Boy (family|boy|girl|parents)
👨‍👩‍👦‍👦 Family: Man, Woman, Boy, Boy (family|two|boys|parents)
👨‍👩‍👧‍👧 Family: Man, Woman, Girl, Girl (family|two|girls|parents)
👨‍👨‍👦 Family: Man, Man, Boy (family|dads|boy|child)
👨‍👨‍👧 Family: Man, Man, Girl (family|dads|girl|child)
👨‍👨‍👧‍👦 Family: Man, Man, Girl, Boy (family|dads|children|kids)
👨‍👨‍👦‍👦 Family: Man, Man, Boy, Boy (family|dads|boys|kids)
👨‍👨‍👧‍👧 Family: Man, Man, Girl, Girl (family|dads|girls|kids)
👩‍👩‍👦 Family: Woman, Woman, Boy (family|moms|boy|child)
👩‍👩‍👧 Family: Woman, Woman, Girl (family|moms|girl|child)
👩‍👩‍👧‍👦 Family: Woman, Woman, Girl, Boy (family|moms|children|kids)
👩‍👩‍👦‍👦 Family: Woman, Woman, Boy, Boy (family|moms|boys|kids)
👩‍👩‍👧‍👧 Family: Woman, Woman, Girl, Girl (family|moms|girls|kids)
👨‍👦 Family: Man, Boy (dad|boy|child|son)
👨‍👦‍👦 Family: Man, Boy, Boy (dad|two|boys|sons)
👨‍👧 Family: Man, Girl (dad|girl|child|daughter)
👨‍👧‍👦 Family: Man, Girl, Boy (dad|boy|girl|kids)
👨‍👧‍👧 Family: Man, Girl, Girl (dad|two|girls|daughters)
👩‍👦 Family: Woman, Boy (mom|boy|child|son)
👩‍👦‍👦 Family: Woman, Boy, Boy (mom|two|boys|sons)
👩‍👧 Family: Woman, Girl (mom|girl|child|daughter)
👩‍👧‍👦 Family: Woman, Girl, Boy (mom|boy|girl|kids)
👩‍👧‍👧 Family: Woman, Girl, Girl (mom|two|girls|daughters)
🗣️ Speaking Head (speaking|head|talk|shout|yell)
👤 Bust in Silhouette (silhouette|user|person|profile|shadow)
👥 Busts in Silhouette (silhouettes|group|team|users|people)
👣 Footprints (footprints|feet|walking|steps|tracks)
🐵 Monkey Face (monkey|face|animal|ape|primate)
🐒 Monkey (monkey|animal|banana|ape|primate)
🦍 Gorilla (gorilla|ape|animal|silverback)
🦧 Orangutan (orangutan|ape|animal|monkey)
🐶 Dog Face (dog|face|puppy|pet|animal)
🐕 Dog (dog|pet|animal|canine)
🦮 Guide Dog (guide|dog|blind|access|pet)
🐕‍🦺 Service Dog (service|dog|access|vest|pet)
🐩 Poodle (poodle|dog|pet|animal)
🐺 Wolf (wolf|wild|animal|dog|howl)
🦊 Fox (fox|face|animal|wild|orange)
🦝 Raccoon (raccoon|animal|pet|trashpanda)
🐱 Cat Face (cat|face|meow|pet|kitten)
🐈 Cat (cat|pet|animal|feline)
🦁 Lion (lion|king|animal|wild|roar)
🐯 Tiger Face (tiger|face|wild|cat|roar)
🐅 Tiger (tiger|wild|cat|animal|stripes)
🐆 Leopard (leopard|spotted|cat|wild|safari)
🐴 Horse Face (horse|face|brown|animal|neigh)
🐎 Horse (horse|racing|speed|animal|gallop)
🦄 Unicorn (unicorn|magic|horse|fantasy|horn)
🦓 Zebra (zebra|safari|stripes|animal|wild)
🦌 Deer (deer|horns|nature|animal|buck)
🐮 Cow Face (cow|face|moo|animal|farm)
🐂 Ox (ox|bull|cattle|farm|animal)
🐃 Water Buffalo (water|buffalo|ox|animal)
🐄 Cow (cow|milk|moo|farm|cattle)
🐷 Pig Face (pig|face|oink|farm|animal)
🐖 Pig (pig|pork|animal|farm)
🐗 Boar (boar|wild|pig|animal|tusks)
🐽 Pig Nose (pig|nose|oink|animal|snout)
🐏 Ram (ram|sheep|horns|animal|farm)
🐑 Ewe (ewe|sheep|wool|animal|farm)
🐐 Goat (goat|animal|nature|farm|horns)
🐪 Camel (camel|desert|hump|animal)
🐫 Two-Hump Camel (camel|two|humps|desert|animal)
🦙 Llama (llama|alpaca|animal|farm)
🦒 Giraffe (giraffe|tall|safari|animal|wild)
🐘 Elephant (elephant|trunk|animal|wild|safari)
🦏 Rhinoceros (rhinoceros|horn|animal|rhino|wild)
🦛 Hippopotamus (hippopotamus|hippo|animal|wild|water)
🐭 Mouse Face (mouse|face|rodent|animal|cheese)
🐁 Mouse (mouse|rodent|white|animal|pet)
🐀 Rat (rat|rodent|animal|pest)
🐹 Hamster (hamster|pet|rodent|animal|cute)
🐰 Rabbit Face (rabbit|face|bunny|pet|animal)
🐇 Rabbit (rabbit|bunny|pet|animal|hop)
🐿️ Chipmunk (chipmunk|squirrel|rodent|animal|nut)
🦔 Hedgehog (hedgehog|spiny|animal|cute|pet)
🦇 Bat (bat|vampire|animal|fly|night)
🐻 Bear (bear|wild|animal|nature)
🐨 Koala (koala|australia|bear|animal|cute)
🐼 Panda (panda|bamboo|bear|animal|cute)
🦥 Sloth (sloth|slow|animal|lazy|tree)
🦦 Otter (otter|water|animal|cute|swim)
🦨 Skunk (skunk|smelly|animal|stink|wild)
🦘 Kangaroo (kangaroo|australia|hop|animal|pouch)
🦡 Badger (badger|animal|nature|wild)
🐾 Paw Prints (paw|prints|feet|animal|tracks)
🦃 Turkey (turkey|bird|thanksgiving|animal)
🐔 Chicken (chicken|cluck|bird|farm|poultry)
🐓 Rooster (rooster|cock|bird|farm|morning)
🐣 Hatching Chick (hatching|chick|egg|bird|baby)
🐤 Baby Chick (baby|chick|bird|cute|yellow)
🐥 Front-Facing Baby Chick (baby|chick|front|bird|cute)
🐦 Bird (bird|tweet|fly|animal|nature)
🐧 Penguin (penguin|ice|bird|cold|animal)
🕊️ Dove (dove|peace|bird|white|fly)
🦅 Eagle (eagle|raptor|bird|wild|fly)
🦆 Duck (duck|mallard|bird|quack|water)
🦢 Swan (swan|white|bird|water|elegant)
🦉 Owl (owl|hoot|bird|night|wise)
🦩 Flamingo (flamingo|pink|bird|water|animal)
🦚 Peacock (peacock|bird|feathers|colorful|animal)
🦜 Parrot (parrot|pirate|bird|tropical|colorful)
🐸 Frog (frog|toad|croak|animal|green)
🐊 Crocodile (crocodile|gator|reptile|animal|teeth)
🐢 Turtle (turtle|tortoise|slow|reptile|animal)
🦎 Lizard (lizard|reptile|animal|gecko)
🐍 Snake (snake|python|hiss|reptile|animal)
🫯 Cloud Fight (cloud|fight|dust|brawl|comic)
🐲 Dragon Face (dragon|face|myth|fantasy|creature)
🐉 Dragon (dragon|myth|green|fantasy|creature)
🦕 Sauropod (sauropod|dinosaur|extinct|animal|brontosaurus)
🦖 T-Rex (trex|dinosaur|extinct|animal|roar)
🐳 Spouting Whale (spouting|whale|ocean|sea|water)
🐋 Whale (whale|ocean|sea|animal|water)
🐬 Dolphin (dolphin|flipper|ocean|sea|water)
🐟 Fish (fish|swim|water|ocean|sea)
🐠 Tropical Fish (tropical|fish|nemo|ocean|sea)
🐡 Blowfish (blowfish|sea|food|ocean|fish)
🦈 Shark (shark|jaws|ocean|sea|fish)
🐙 Octopus (octopus|tentacles|sea|ocean|animal)
🐚 Spiral Shell (spiral|shell|beach|ocean|sea)
🐌 Snail (snail|slow|shell|animal|bug)
🦋 Butterfly (butterfly|insect|wings|beautiful|nature)
🐛 Bug (bug|caterpillar|worm|insect|nature)
🐜 Ant (ant|insect|bug|nature|small)
🐝 Honeybee (honeybee|bee|honey|insect|buzz)
🐞 Ladybug (ladybug|beetle|insect|bug|red)
🦗 Cricket (cricket|chirp|insect|bug|jump)
🕷️ Spider (spider|arachnid|web|bug|scary)
🕸️ Spider Web (spider|web|silk|halloween|spooky)
🦂 Scorpion (scorpion|arachnid|hazard|bug|sting)
🦟 Mosquito (mosquito|bug|malaria|insect|bite)
🦠 Microbe (microbe|germ|virus|bacteria|sick)
💐 Bouquet (bouquet|flowers|spring|gift|love)
🌸 Cherry Blossom (cherry|blossom|pink|flower|spring)
💮 White Flower (white|flower|japanese|stamp|spring)
🏵️ Rosette (rosette|flower|military|decoration|yellow)
🌹 Rose (rose|red|love|flower|romance)
🥀 Wilted Flower (wilted|flower|dead|sad|rose)
🌺 Hibiscus (hibiscus|tropical|flower|hawaii|summer)
🌻 Sunflower (sunflower|yellow|plant|flower|summer)
🌼 Blossom (blossom|yellow|flower|spring|nature)
🌷 Tulip (tulip|spring|flower|plant|nature)
🌱 Seedling (seedling|plant|sprout|nature|grow)
🌲 Evergreen Tree (evergreen|tree|pine|nature|forest)
🌳 Deciduous Tree (deciduous|tree|nature|forest|wood)
🌴 Palm Tree (palm|tree|tropical|beach|summer)
🌵 Cactus (cactus|desert|plant|nature|spike)
🌾 Sheaf of Rice (sheaf|rice|grain|plant|farm)
🌿 Herb (herb|plant|leaf|nature|green)
☘️ Shamrock (shamrock|irish|clover|luck|green)
🍀 Four Leaf Clover (four|leaf|clover|luck|irish|green)
🍁 Maple Leaf (maple|leaf|autumn|fall|canada)
🍂 Fallen Leaf (fallen|leaf|autumn|fall|nature)
🍃 Leaf Fluttering in Wind (leaf|wind|fluttering|nature|breeze)
🍇 Grapes (grapes|fruit|wine|food|purple)
🍈 Melon (melon|fruit|sweet|food|cantaloupe)
🍉 Watermelon (watermelon|fruit|summer|food|sweet)
🍊 Tangerine (tangerine|orange|fruit|citrus|food)
🍋 Lemon (lemon|sour|fruit|citrus|food)
🍌 Banana (banana|monkey|fruit|food|yellow)
🍍 Pineapple (pineapple|tropical|fruit|food|sweet)
🥭 Mango (mango|fruit|tropical|food|sweet)
🍎 Red Apple (red|apple|fruit|food|school)
🍏 Green Apple (green|apple|fruit|food|sour)
🍐 Pear (pear|fruit|nature|food|green)
🍑 Peach (peach|fruit|fuzzy|food|butt)
🍒 Cherries (cherries|red|fruit|food|sweet)
🍓 Strawberry (strawberry|red|fruit|food|sweet)
🥝 Kiwi (kiwi|fruit|food|green|tropical)
🍅 Tomato (tomato|red|fruit|food|veg)
🥥 Coconut (coconut|tropical|nut|food|fruit)
🥑 Avocado (avocado|guacamole|fruit|food|veg)
🍆 Eggplant (eggplant|vegetable|food|purple|aubergine)
🥔 Potato (potato|veg|starch|food|spud)
🥕 Carrot (carrot|orange|veg|food|bunny)
🌽 Ear of Corn (ear|corn|yellow|veg|food|maize)
🌶️ Hot Pepper (hot|pepper|chili|spicy|food)
🥒 Cucumber (cucumber|pickle|veg|food|green)
🥬 Leafy Green (leafy|green|lettuce|veg|food)
🥦 Broccoli (broccoli|green|veg|food|healthy)
🧄 Garlic (garlic|spice|food|veg|cook)
🧅 Onion (onion|cook|veg|food|cry)
🍄 Mushroom (mushroom|fungus|plant|food|toadstool)
🥜 Peanuts (peanuts|nut|snack|food|legume)
🌰 Chestnut (chestnut|squirrel|nut|food|autumn)
🍞 Bread (bread|slice|toast|food|carb)
🥐 Croissant (croissant|french|pastry|food|bread)
🥖 Baguette (baguette|french|bread|food|loaf)
🥨 Pretzel (pretzel|twisted|bread|food|snack)
🥯 Bagel (bagel|bakery|toast|food|bread)
🥞 Pancakes (pancakes|breakfast|flapjacks|food|syrup)
🧇 Waffle (waffle|breakfast|syrup|food|iron)
🧀 Cheese Wedge (cheese|wedge|food|dairy|mouse)
🍖 Meat on Bone (meat|bone|drumstick|food|bbq)
🍗 Poultry Leg (poultry|leg|chicken|food|meat)
🥩 Cut of Meat (cut|meat|steak|food|beef)
🥓 Bacon (bacon|pork|strip|food|meat|breakfast)
🍔 Hamburger (hamburger|cheeseburger|fastfood|food|burger)
🍟 French Fries (french|fries|chips|fastfood|food|potato)
🍕 Pizza (pizza|slice|party|food|fastfood)
🌭 Hot Dog (hot|dog|frankfurter|food|sausage|fastfood)
🥪 Sandwich (sandwich|lunch|bread|food|deli)
🌮 Taco (taco|mexican|food|shell|fastfood)
🌯 Burrito (burrito|mexican|food|wrap|fastfood)
🥙 Flatbread (flatbread|gyro|wrap|food|kebab)
🧆 Falafel (falafel|chickpea|ball|food|middleeast)
🥚 Egg (egg|chicken|breakfast|food|oval)
🍳 Fried Egg (fried|egg|cooking|food|breakfast|pan)
🥘 Shallow Pan of Food (shallow|pan|paella|food|cooking)
🍲 Pot of Food (pot|food|soup|stew|cooking)
🥣 Bowl with Spoon (bowl|spoon|cereal|soup|food)
🥗 Green Salad (green|salad|healthy|food|veg)
🍿 Popcorn (popcorn|movie|cinema|food|snack)
🧈 Butter (butter|dairy|cooking|food|yellow)
🧂 Salt (salt|shaker|spice|food|seasoning)
🥫 Canned Food (canned|food|soup|tin|grocery)
🍱 Bento Box (bento|box|japanese|food|lunch)
🍘 Rice Cracker (rice|cracker|japanese|food|snack)
🍙 Rice Ball (rice|ball|japanese|food|onigiri)
🍚 Cooked Rice (cooked|rice|bowl|food|asian)
🍛 Curry Rice (curry|rice|indian|food|spicy)
🍜 Steaming Noodles (steaming|noodles|ramen|food|asian|soup)
🍝 Spaghetti (spaghetti|pasta|italian|food|noodles)
🍠 Roasted Sweet Potato (roasted|sweet|potato|food|yam)
🍢 Oden (oden|japanese|food|skewer|snack)
🍣 Sushi (sushi|raw|fish|japanese|food|rice)
🍤 Fried Shrimp (fried|shrimp|tempura|food|seafood)
🍥 Fish Cake with Swirl (fish|cake|swirl|food|japanese|ramen)
🥮 Mooncake (mooncake|autumn|festival|food|chinese)
🍡 Dango (dango|sweet|skewers|food|japanese|mochi)
🥟 Dumpling (dumpling|potsticker|food|asian)
🥠 Fortune Cookie (fortune|cookie|prophecy|food|chinese)
🥡 Takeout Box (takeout|box|chinese|food|delivery|oyster)
🦀 Crab (crab|seafood|crustacean|animal|ocean)
🦞 Lobster (lobster|seafood|claws|animal|ocean)
🦐 Shrimp (shrimp|seafood|ocean|animal|food)
🦑 Squid (squid|ocean|seafood|animal|calamari)
🦪 Oyster (oyster|seafood|shell|food|pearl)
🍦 Soft Ice Cream (soft|ice|cream|dessert|sweet)
🍧 Shaved Ice (shaved|ice|dessert|sweet|summer)
🍨 Ice Cream (ice|cream|bowl|dessert|sweet)
🍩 Doughnut (doughnut|donut|sweet|dessert|pastry)
🍪 Cookie (cookie|chocolate|sweet|dessert|biscuit)
🎂 Birthday Cake (birthday|cake|party|dessert|sweet)
🍰 Shortcake (shortcake|slice|cake|dessert|sweet)
🧁 Cupcake (cupcake|bakery|sweet|dessert|cake)
🥧 Pie (pie|pastry|dessert|sweet|food)
🍫 Chocolate Bar (chocolate|bar|sweet|dessert|candy)
🍬 Candy (candy|lolly|sweet|dessert|treat)
🍭 Lollipop (lollipop|candy|sweet|dessert|treat)
🍮 Custard (custard|pudding|dessert|sweet|flan)
🍯 Honey Pot (honey|pot|bee|sweet|food)
🍼 Baby Bottle (baby|bottle|milk|drink|infant)
🥛 Glass of Milk (glass|milk|drink|dairy|cow)
☕ Hot Beverage (hot|coffee|tea|drink|cafe)
🍵 Teacup Without Handle (teacup|green|tea|drink|matcha)
🍶 Sake (sake|wine|japanese|drink|alcohol)
🍾 Bottle with Popping Cork (popping|cork|champagne|drink|celebration)
🍷 Wine Glass (wine|glass|alcohol|drink|red)
🍸 Cocktail Glass (cocktail|glass|booze|drink|martini)
🍹 Tropical Drink (tropical|drink|beach|alcohol|cocktail)
🍺 Beer Mug (beer|mug|pub|drink|alcohol|pint)
🍻 Clinking Beer Mugs (clinking|beers|cheers|drink|alcohol|party)
🥂 Clinking Glasses (clinking|glasses|toast|drink|champagne|celebration)
🥃 Tumbler Glass (tumbler|glass|whiskey|drink|alcohol|liquor)
🥤 Cup with Straw (cup|straw|soda|drink|fastfood)
🧃 Beverage Box (juice|box|drink|apple|sweet)
🧉 Mate (mate|tea|drink|herb|caffeine)
🧊 Ice (ice|cold|cube|water|freeze)
🥢 Chopsticks (chopsticks|utensils|food|asian|eat)
🍽️ Fork and Knife with Plate (plate|knife|fork|dining|eat)
🍴 Fork and Knife (knife|fork|cutlery|eat|utensils)
🥄 Spoon (spoon|cutlery|kitchen|eat|soup)
🔪 Kitchen Knife (kitchen|knife|blade|cut|cooking)
🏺 Amphora (amphora|vase|jar|ancient|pottery)
🌍 Globe Showing Europe-Africa (globe|europe|africa|world|earth)
🌎 Globe Showing Americas (globe|americas|usa|world|earth)
🌏 Globe Showing Asia-Australia (globe|asia|australia|world|earth)
🌐 Globe with Meridians (globe|meridians|internet|world|web)
🗺️ World Map (world|map|location|geography|travel)
🗾 Map of Japan (map|japan|country|geography|travel)
🧭 Compass (compass|navigation|direction|travel|north)
🏔️ Snow-Capped Mountain (snow|mountain|cold|nature|hike)
⛰️ Mountain (mountain|nature|photo|hike|landscape)
🌋 Volcano (volcano|eruption|disaster|mountain|lava)
🗻 Mount Fuji (mount|fuji|japan|mountain|nature)
🏕️ Camping (camping|tent|outdoors|nature|camp)
🏖️ Beach with Umbrella (beach|umbrella|summer|ocean|sand)
🏜️ Desert (desert|sahara|sand|nature|hot)
🏝️ Desert Island (desert|island|tropical|beach|ocean)
🏞️ National Park (national|park|nature|landscape|photo)
🏟️ Stadium (stadium|sports|concert|arena|event)
🏛️ Classical Building (classical|building|culture|architecture|museum)
🏗️ Building Construction (building|construction|wip|crane|work)
🧱 Brick (brick|wall|building|construction|masonry)
🏘️ Houses (houses|neighbourhood|building|homes|suburb)
🏚️ Derelict House (derelict|house|broken|abandoned|ruin)
🏠 House (house|home|building|residence|door)
🏡 House with Garden (house|garden|home|building|yard)
🏢 Office Building (office|building|work|city|business)
🏣 Japanese Post Office (japanese|post|office|mail|building)
🏤 Post Office (post|office|mail|building|letters)
🏥 Hospital (hospital|health|doctor|medical|building)
🏦 Bank (bank|money|cash|building|finance)
🏨 Hotel (hotel|accommodation|checkin|building|vacation)
🏩 Love Hotel (love|hotel|dating|building|heart)
🏪 Convenience Store (convenience|store|groceries|building|shop)
🏫 School (school|education|learn|building|class)
🏬 Department Store (department|store|mall|building|shopping)
🏭 Factory (factory|industry|smoke|building|manufacturing)
🏯 Japanese Castle (japanese|castle|historic|building|architecture)
🏰 Castle (castle|royalty|history|building|fortress)
💒 Wedding (wedding|chapel|marriage|church|love)
🗼 Tokyo Tower (tokyo|tower|japan|architecture|landmark)
🗽 Statue of Liberty (statue|liberty|newyork|monument|usa)
⛪ Church (church|religion|christ|building|cross)
🕌 Mosque (mosque|islam|worship|religion|building)
🛕 Hindu Temple (hindu|temple|religion|worship|building)
🕍 Synagogue (synagogue|judaism|temple|religion|building)
⛩️ Shinto Shrine (shinto|shrine|japan|religion|temple)
🕋 Kaaba (kaaba|mecca|islam|religion|worship)
⛲ Fountain (fountain|water|fresh|park|spring)
⛺ Tent (tent|camping|outdoor|nature|camp)
🌁 Foggy (foggy|fog|mountain|bridge|weather)
🌃 Night with Stars (night|stars|city|evening|sky)
🏙️ Cityscape (cityscape|urban|skyline|city|buildings)
🌄 Sunrise Over Mountains (sunrise|mountains|morning|nature|dawn)
🌅 Sunrise (sunrise|ocean|morning|beach|dawn)
🌆 Cityscape at Dusk (cityscape|dusk|evening|city|sunset)
🌇 Sunset (sunset|city|dawn|buildings|evening)
🌉 Bridge at Night (bridge|night|sf|city|water)
♨️ Hot Springs (hot|springs|bath|steam|relax)
🎠 Carousel Horse (carousel|horse|carnival|amusement|ride)
🎡 Ferris Wheel (ferris|wheel|carnival|amusement|ride)
🎢 Roller Coaster (roller|coaster|fun|amusement|ride|carnival)
💈 Barber Pole (barber|pole|salon|haircut|stripes)
🎪 Circus Tent (circus|tent|festival|carnival|show)
🚂 Locomotive (locomotive|train|vintage|transport|steam)
🚃 Railway Car (railway|car|train|transport|transit)
🚄 High-Speed Train (high|speed|train|transport|fast)
🚅 Bullet Train (bullet|train|fast|transport|shinkansen)
🚆 Train (train|transport|public|transit|railway)
🚇 Metro (metro|subway|tube|train|transport|underground)
🚈 Light Rail (light|rail|train|transport|transit)
🚉 Station (station|train|platform|transport|transit)
🚊 Tram (tram|transport|public|transit|city)
🚝 Monorail (monorail|train|transport|transit|rail)
🚞 Mountain Railway (mountain|railway|train|transport|transit)
🚋 Tram Car (tram|car|public|transport|transit)
🚌 Bus (bus|transport|public|transit|vehicle)
🚍 Oncoming Bus (oncoming|bus|transport|public|vehicle)
🚎 Trolleybus (trolleybus|transport|public|bus|vehicle)
🚐 Minibus (minibus|transport|van|vehicle|car)
🚑 Ambulance (ambulance|health|emergency|hospital|vehicle)
🚒 Fire Engine (fire|engine|911|truck|emergency|vehicle)
🚓 Police Car (police|car|cop|emergency|vehicle|law)
🚔 Oncoming Police Car (oncoming|police|car|emergency|vehicle|cop)
🚕 Taxi (taxi|cab|uber|transport|vehicle|yellow)
🚖 Oncoming Taxi (oncoming|taxi|cab|transport|vehicle)
🚗 Automobile (automobile|car|red|vehicle|transport|drive)
🚘 Oncoming Automobile (oncoming|automobile|car|vehicle|transport)
🚙 Sport Utility Vehicle (suv|sport|utility|car|vehicle|transport)
🚚 Delivery Truck (delivery|truck|transport|vehicle|shipping)
🚛 Articulated Lorry (articulated|lorry|truck|transport|vehicle|shipping)
🚜 Tractor (tractor|farm|agriculture|vehicle|transport)
🏎️ Racing Car (racing|car|f1|sports|vehicle|fast)
🏍️ Motorcycle (motorcycle|race|fast|bike|vehicle|transport)
🛵 Motor Scooter (motor|scooter|vespa|bike|vehicle|transport)
🦽 Manual Wheelchair (manual|wheelchair|access|mobility|transport)
🦼 Motorized Wheelchair (motorized|wheelchair|access|mobility|transport)
🛺 Auto Rickshaw (auto|rickshaw|tuktuk|transport|vehicle|asia)
🚲 Bicycle (bicycle|bike|exercise|transport|pedal)
🛴 Kick Scooter (kick|scooter|razor|transport|ride)
🛹 Skateboard (skateboard|board|skate|sport|ride)
🚏 Bus Stop (bus|stop|transit|transport|wait)
🛣️ Motorway (motorway|highway|road|street|drive)
🛤️ Railway Track (railway|track|train|transport|rail)
🛢️ Oil Drum (oil|drum|barrel|fuel|industry)
⛽ Fuel Pump (fuel|pump|gas|station|petrol|car)
🚨 Police Car Light (police|light|emergency|siren|alarm)
🚥 Horizontal Traffic Light (horizontal|traffic|light|stop|go)
🚦 Vertical Traffic Light (vertical|traffic|light|stop|go)
🛑 Stop Sign (stop|sign|halt|warning|red)
🚧 Construction (construction|sign|warning|road|work|barrier)
⚓ Anchor (anchor|ship|sea|ocean|boat)
⛵ Sailboat (sailboat|wind|water|boat|sea)
🛶 Canoe (canoe|paddle|boat|water|river)
🚤 Speedboat (speedboat|fast|water|boat|sea)
🛳️ Passenger Ship (passenger|ship|cruise|boat|ocean)
⛴️ Ferry (ferry|boat|ship|water|transport)
🛥️ Motorboat (motorboat|ship|sea|boat|water)
🚢 Ship (ship|titanic|vessel|boat|ocean|sea)
✈️ Airplane (airplane|flight|fly|plane|travel)
🛩️ Small Airplane (small|airplane|fly|plane|travel)
🛫 Airplane Departure (airplane|departure|takeoff|flight|fly)
🛬 Airplane Arrival (airplane|arrival|landing|flight|fly)
🪂 Parachute (parachute|skydiving|glide|fly|fall)
💺 Seat (seat|flight|sit|chair|airplane)
🚁 Helicopter (helicopter|copter|fly|aircraft|travel)
🚟 Suspension Railway (suspension|railway|transit|train|transport)
🚠 Mountain Cableway (mountain|cableway|ski|gondola|transport)
🚡 Aerial Tramway (aerial|tramway|ski|gondola|transport)
🛰️ Satellite (satellite|space|orbit|communication|tech)
🚀 Rocket (rocket|launch|nasa|space|ship|fly)
🛸 Flying Saucer (flying|saucer|ufo|alien|space|ship)
🛎️ Bellhop Bell (bellhop|bell|service|hotel|reception)
🧳 Luggage (luggage|suitcase|travel|bag|trip)
⌛ Hourglass Done (hourglass|done|time|sand|clock)
⏳ Hourglass Not Done (hourglass|countdown|time|sand|wait)
⌚ Watch (watch|wrist|time|clock|wearable)
⏰ Alarm Clock (alarm|clock|wake|time|morning)
⏱️ Stopwatch (stopwatch|timer|deadline|time|clock|race)
⏲️ Timer Clock (timer|clock|alarm|time|kitchen)
🕰️ Mantelpiece Clock (mantelpiece|clock|time|antique|furniture)
🕛 Twelve O’Clock (twelve|clock|noon|time|12:00)
🕧 Twelve-Thirty (twelve|thirty|time|clock|12:30)
🕐 One O’Clock (one|clock|time|1:00)
🕜 One-Thirty (one|thirty|time|clock|1:30)
🕑 Two O’Clock (two|clock|time|2:00)
🕝 Two-Thirty (two|thirty|time|clock|2:30)
🕒 Three O’Clock (three|clock|time|3:00)
🕞 Three-Thirty (three|thirty|time|clock|3:30)
🕓 Four O’Clock (four|clock|time|4:00)
🕟 Four-Thirty (four|thirty|time|clock|4:30)
🕔 Five O’Clock (five|clock|time|5:00)
🕠 Five-Thirty (five|thirty|time|clock|5:30)
🕕 Six O’Clock (six|clock|evening|time|6:00)
🕡 Six-Thirty (six|thirty|time|clock|6:30)
🕖 Seven O’Clock (seven|clock|time|7:00)
🕢 Seven-Thirty (seven|thirty|time|clock|7:30)
🕗 Eight O’Clock (eight|clock|time|8:00)
🕣 Eight-Thirty (eight|thirty|time|clock|8:30)
🕘 Nine O’Clock (nine|clock|time|9:00)
🕤 Nine-Thirty (nine|thirty|time|clock|9:30)
🕙 Ten O’Clock (ten|clock|time|10:00)
🕥 Ten-Thirty (ten|thirty|time|clock|10:30)
🕚 Eleven O’Clock (eleven|clock|time|11:00)
🕦 Eleven-Thirty (eleven|thirty|time|clock|11:30)
🌑 new moon night (moon|lunar|night|space|sky|dark|new)
🌒 waxing crescent moon (moon|lunar|night|space|sky|crescent|waxing)
🌓 first quarter moon (moon|lunar|night|space|sky|quarter|first)
🌔 waxing gibbous moon (moon|lunar|night|space|sky|gibbous|waxing)
🌕 full moon yellow (moon|lunar|night|space|sky|full|yellow)
🌖 waning gibbous moon (moon|lunar|night|space|sky|gibbous|waning)
🌗 last quarter moon (moon|lunar|night|space|sky|quarter|last)
🌘 waning crescent moon (moon|lunar|night|space|sky|crescent|waning)
🌙 crescent moon night (moon|lunar|night|space|sky|crescent)
🌚 new moon face (moon|lunar|night|space|sky|face|new)
🌛 first quarter face (moon|lunar|night|space|sky|face|quarter|first)
🌜 last quarter face (moon|lunar|night|space|sky|face|quarter|last)
🌡️ thermometer temperature weather (thermometer|temperature|weather|hot|cold|temp)
☀️ sun sunny brightness (sun|sunny|bright|day|light|weather)
🌝 full moon face (moon|lunar|night|space|sky|face|full)
🌞 sun face morning (sun|sunny|face|morning|day|light)
🪐 ringed planet saturn (planet|saturn|space|ring|astronomy)
⭐ star yellow night (star|yellow|night|space|sky)
🌟 glowing star sparkle (star|glow|sparkle|shine|space|night)
🌠 shooting star wish (star|shooting|wish|space|night|meteor)
🌌 milky way space (milky way|galaxy|space|stars|night)
☁️ cloud weather sky (cloud|weather|sky|forecast)
⛅ sun behind cloud (sun|cloud|weather|partly|sky)
⛈️ cloud lightning rain (cloud|lightning|rain|storm|thunder|weather)
🌤️ sun small cloud (sun|cloud|weather|partly|sky)
🌥️ sun large cloud (sun|cloud|weather|overcast|sky)
🌦️ sun rain cloud (sun|rain|cloud|weather|shower)
🌧️ cloud rain weather (cloud|rain|weather|wet|storm)
🌨️ cloud snow weather (cloud|snow|weather|winter|cold)
🌩️ cloud lightning thunder (cloud|lightning|thunder|storm|weather)
🌪️ tornado cyclone twister (tornado|cyclone|twister|storm|wind|weather)
🌫️ fog weather mist (fog|mist|weather|haze|cloud)
🌬️ wind face blowing (wind|blowing|face|weather|air)
🌀 cyclone vortex spiral (cyclone|vortex|spiral|storm|wind|weather)
🌈 rainbow colorful sky (rainbow|colorful|sky|weather|pride)
🌂 closed umbrella rain (umbrella|closed|rain|weather|wet)
☂️ umbrella weather rain (umbrella|weather|rain|wet)
☔ umbrella rain drops (umbrella|rain|drops|weather|wet)
⛱️ umbrella ground beach (umbrella|beach|ground|sun|summer)
⚡ high voltage lightning (lightning|voltage|electric|storm|power|zap)
❄️ snowflake winter cold (snowflake|winter|cold|snow|ice|weather)
☃️ snowman winter xmas (snowman|winter|christmas|xmas|snow)
⛄ snowman no snow (snowman|winter|snow|no snow)
☄️ comet space meteor (comet|space|meteor|astronomy|sky)
🔥 fire flame hot (fire|flame|hot|burn|lit)
💧 droplet water drip (droplet|water|drip|drop|liquid)
🌊 water wave ocean (water|wave|ocean|sea|liquid)
🎃 jack lantern halloween (pumpkin|jack o lantern|halloween|spooky)
🎄 christmas tree xmas (christmas tree|xmas|holiday|festive)
🎆 fireworks festival celebration (fireworks|festival|celebration|party|new year)
🎇 sparkler shine night (sparkler|shine|night|fireworks|party)
🧨 firecracker dynamite boom (firecracker|dynamite|boom|explosive|party)
✨ sparkles shiny magic (sparkles|shiny|magic|star|glitter)
🎈 balloon party birthday (balloon|party|birthday|celebration)
🎉 party popper tada (party popper|tada|party|celebration|confetti)
🎊 confetti ball party (confetti|ball|party|celebration)
🎋 tanabata tree japan (tanabata|tree|japan|festival|wish)
🎍 pine decoration japan (pine|decoration|japan|new year)
🎎 japanese dolls toy (japanese|dolls|toy|festival|hina)
🎏 carp streamer banner (carp|streamer|banner|japan|children day)
🎐 wind chime spring (wind chime|spring|bell|japan|summer)
🎑 moon viewing ceremony (moon viewing|ceremony|japan|autumn|tsukimi)
🧧 red envelope gift (red envelope|gift|hongbao|chinese new year|money)
🎀 ribbon bowtie pink (ribbon|bowtie|pink|gift|decoration)
🎁 wrapped gift present (gift|present|wrapped|box|birthday)
🎗️ reminder ribbon cause (reminder|ribbon|cause|awareness|support)
🎟️ admission tickets concert (admission|tickets|concert|event|pass)
🎫 ticket event pass (ticket|event|pass|admission)
🎖️ military medal award (military|medal|award|honor|ribbon)
🏆 trophy winner cup (trophy|winner|cup|award|champion)
🏅 sports medal award (sports|medal|award|winner|honor)
🥇 1st place medal (1st|first|place|medal|gold|winner)
🥈 2nd place medal (2nd|second|place|medal|silver|winner)
🥉 3rd place medal (3rd|third|place|medal|bronze|winner)
⚽ soccer ball football (soccer|ball|football|sport|game)
⚾ baseball sport ball (baseball|sport|ball|game)
🥎 softball sport ball (softball|sport|ball|game)
🏀 basketball nba ball (basketball|nba|ball|sport|game)
🏐 volleyball sport ball (volleyball|sport|ball|game)
🏈 american football nfl (american football|nfl|ball|sport|game)
🏉 rugby football sport (rugby|football|sport|ball|game)
🎾 tennis racket ball (tennis|racket|ball|sport|game)
🥏 flying disc frisbee (flying disc|frisbee|sport|game|disc)
🎳 bowling ball pins (bowling|ball|pins|sport|game)
🏏 cricket bat ball (cricket|bat|ball|sport|game)
🏑 field hockey stick (field hockey|stick|sport|game|hockey)
🏒 ice hockey puck (ice hockey|puck|sport|game|hockey)
🥍 lacrosse stick ball (lacrosse|stick|ball|sport|game)
🏓 ping pong table (ping pong|table tennis|sport|game|paddle)
🏸 badminton shuttlecock sport (badminton|shuttlecock|sport|game|racket)
🥊 boxing glove fight (boxing|glove|fight|sport|punch)
🥋 martial arts gi (martial arts|gi|karate|judo|sport)
🥅 goal net sports (goal|net|sports|game|soccer)
⛳ flag hole golf (flag|hole|golf|sport|game)
⛸️ ice skate winter (ice skate|winter|skate|sport|cold)
🎣 fishing pole rod (fishing|pole|rod|sport|fish)
🤿 diving mask snorkel (diving|mask|snorkel|swim|underwater)
🎽 running shirt sash (running|shirt|sash|sport|marathon)
🎿 skis winter snow (skis|winter|snow|sport|ski)
🛷 sled sleigh luge (sled|sleigh|luge|winter|snow)
🥌 curling stone sport (curling|stone|sport|game|ice)
🎯 direct hit bullseye (direct hit|bullseye|target|dart|game)
🪀 yoyo toy spin (yoyo|toy|spin|game|play)
🪁 kite fly wind (kite|fly|wind|toy|play)
🎱 pool 8ball billiards (pool|8ball|billiards|game|ball)
🔮 crystal ball fortune (crystal ball|fortune|magic|predict|future)
🧿 nazar amulet evil-eye (nazar|amulet|evil eye|protection|talisman)
🎮 video game controller (video game|controller|game|play|gaming)
🕹️ joystick arcade controller (joystick|arcade|controller|game|retro)
🎰 slot machine casino (slot machine|casino|gamble|game|luck)
🎲 game die dice (game die|dice|random|game|roll)
🧩 puzzle piece jigsaw (puzzle|piece|jigsaw|game|solve)
🧸 teddy bear plush (teddy bear|plush|toy|stuffed|bear)
♠️ spade suit poker (spade|suit|poker|card|game)
♥️ heart suit poker (heart|suit|poker|card|game)
♦️ diamond suit poker (diamond|suit|poker|card|game)
♣️ club suit poker (club|suit|poker|card|game)
♟️ chess pawn game (chess|pawn|game|strategy|piece)
🃏 joker card game (joker|card|game|wild|poker)
🀄 mahjong red dragon (mahjong|red dragon|game|tile|chinese)
🎴 flower cards hanafuda (flower cards|hanafuda|game|japan|card)
🎭 performing arts drama (performing arts|drama|theater|mask|acting)
🖼️ framed picture photo (framed picture|photo|art|frame|image)
🎨 artist palette paint (artist|palette|paint|art|drawing)
🧵 thread spool sewing (thread|spool|sewing|craft|needle)
🧶 yarn ball knit (yarn|ball|knit|craft|wool)
👓 glasses eyesight specs (glasses|eyesight|specs|eyewear|vision)
🕶️ sunglasses cool shades (sunglasses|cool|shades|eyewear|sun)
🥽 goggles safety eyes (goggles|safety|eyes|protection|swim)
🥼 lab coat doctor (lab coat|doctor|science|laboratory|medical)
🦺 safety vest protection (safety vest|protection|construction|work|hi vis)
👔 necktie tie shirt (necktie|tie|shirt|formal|business)
👕 t-shirt tee clothing (t-shirt|tee|clothing|shirt|casual)
👖 jeans pants denim (jeans|pants|denim|clothing|casual)
🧣 scarf neck winter (scarf|neck|winter|clothing|warm)
🧤 gloves winter hands (gloves|winter|hands|clothing|warm)
🧥 coat jacket winter (coat|jacket|winter|clothing|warm)
🧦 socks feet winter (socks|feet|winter|clothing|warm)
👗 dress fashion clothes (dress|fashion|clothes|clothing|woman)
👘 kimono japanese dress (kimono|japanese|dress|clothing|japan)
🥻 sari indian dress (sari|indian|dress|clothing|india)
🩱 swimsuit one-piece (swimsuit|one-piece|swim|clothing|beach)
🩲 briefs underwear clothing (briefs|underwear|clothing|swim|men)
🩳 shorts clothing casual (shorts|clothing|casual|summer|beach)
👙 bikini swimsuit summer (bikini|swimsuit|summer|beach|clothing)
👚 woman s clothes (woman|clothes|clothing|shirt|fashion)
👛 purse coin wallet (purse|coin|wallet|money|accessory)
👜 handbag purse fashion (handbag|purse|fashion|bag|accessory)
👝 clutch bag pouch (clutch|bag|pouch|accessory|fashion)
🛍️ shopping bags mall (shopping|bags|mall|shop|retail)
🎒 backpack school bag (backpack|school|bag|travel|student)
👞 man s shoe (man|shoe|footwear|formal|leather)
👟 running shoe sneaker (running|shoe|sneaker|sport|footwear)
🥾 hiking boot outdoors (hiking|boot|outdoors|shoe|trek)
🥿 flat shoe ballet (flat|shoe|ballet|footwear|woman)
👠 high heel shoe (high heel|shoe|fashion|woman|footwear)
👡 woman s sandal (woman|sandal|shoe|summer|footwear)
🩰 ballet shoes dance (ballet|shoes|dance|footwear|performance)
👢 woman s boot (woman|boot|shoe|winter|footwear)
👑 crown king queen (crown|king|queen|royal|monarch)
👒 woman s hat (woman|hat|fashion|sun|headwear)
🎩 top hat gentleman (top hat|gentleman|formal|magic|hat)
🎓 graduation cap degree (graduation|cap|degree|student|school)
🧢 billed cap hat (billed|cap|hat|baseball|headwear)
⛑️ helmet worker safety (helmet|worker|safety|construction|protection)
📿 prayer beads dhikr (prayer|beads|dhikr|religion|rosary)
💄 lipstick makeup beauty (lipstick|makeup|beauty|cosmetic|woman)
💍 ring diamond proposal (ring|diamond|proposal|wedding|engagement)
💎 gem stone diamond (gem|stone|diamond|jewel|jewelry)
🔇 muted speaker silence (muted|speaker|silence|mute|sound)
🔈 speaker low volume (speaker|low|volume|sound|audio)
🔉 speaker medium volume (speaker|medium|volume|sound|audio)
🔊 speaker high volume (speaker|high|volume|sound|audio)
📢 loudspeaker broadcast (loudspeaker|broadcast|announcement|sound|audio)
📣 megaphone volume (megaphone|volume|announcement|sound|audio)
📯 postal horn music (postal horn|music|horn|sound|instrument)
🔔 bell notification chime (bell|notification|chime|sound|alert)
🔕 bell slash mute (bell slash|mute|silence|no sound|notification off)
🎼 musical score compose (musical score|compose|music|sheet|notes)
🎵 musical note sound (musical note|sound|music|audio|tone)
🎶 musical notes score (musical notes|score|music|audio|tone)
🎙️ studio microphone recording (studio microphone|recording|mic|audio|podcast)
🎚️ level slider scale (level slider|scale|audio|settings|mixer)
🎛️ control knobs dial (control knobs|dial|audio|settings|mixer)
🎤 microphone sing talk (microphone|sing|talk|mic|karaoke)
🎧 headphone music score (headphone|music|score|audio|listen)
📻 radio podcast program (radio|podcast|program|audio|broadcast)
🎷 saxophone jazz blues (saxophone|jazz|blues|music|instrument)
🎸 guitar instrument rock (guitar|instrument|rock|music|strings)
🎹 keyboard piano compose (keyboard|piano|compose|music|instrument)
🎺 trumpet brass instrument (trumpet|brass|instrument|music|horn)
🎻 violin orchestra symphony (violin|orchestra|symphony|music|strings)
🪕 banjo music instrument (banjo|music|instrument|strings|folk)
🥁 drum drumsticks snare (drum|drumsticks|snare|music|percussion)
📱 mobile phone gadget (mobile phone|gadget|cell|smartphone|device)
📲 mobile phone arrow (mobile phone|arrow|call|download|smartphone)
☎️ telephone landline dial (telephone|landline|dial|call|phone)
📞 telephone receiver call (telephone|receiver|call|phone|handset)
📟 pager 90s technology (pager|90s|technology|beeper|retro)
📠 fax machine office (fax machine|office|document|send|retro)
🔋 battery power charger (battery|power|charger|energy|charge)
🔌 electric plug power (electric plug|power|plug|outlet|energy)
💻 laptop computer screen (laptop|computer|screen|pc|device)
🖥️ desktop computer screen (desktop computer|screen|pc|monitor|device)
🖨️ printer paper ink (printer|paper|ink|office|print)
⌨️ keyboard type input (keyboard|type|input|pc|typing)
🖱️ computer mouse click (computer mouse|click|pc|input|cursor)
🖲️ trackball input device (trackball|input|device|pc|mouse)
💽 computer disk 90s (computer disk|90s|storage|retro|disk)
💾 floppy disk save (floppy disk|save|storage|retro|disk)
💿 optical disk cd (optical disk|cd|storage|music|disc)
📀 dvd disc movie (dvd|disc|movie|video|storage)
🧮 abacus math calculation (abacus|math|calculation|count|calculator)
🎥 movie camera film (movie camera|film|cinema|record|video)
🎞️ film frames movie (film frames|movie|cinema|film|video)
📽️ film projector movie (film projector|movie|cinema|projector|video)
🎬 clapper board film (clapper board|film|movie|action|cinema)
📺 television tv show (television|tv|show|screen|broadcast)
📷 camera photography gadget (camera|photography|gadget|photo|picture)
📸 camera flash photo (camera flash|photo|picture|snap|photography)
📹 video camera record (video camera|record|video|film|recording)
📼 videocassette 90s tape (videocassette|90s|tape|retro|vhs)
🔍 magnifying glass search (magnifying glass|search|find|zoom|inspect)
🔎 magnifying glass zoom (magnifying glass|zoom|search|find|inspect)
🕯️ candle fire wax (candle|fire|wax|light|flame)
💡 light bulb idea (light bulb|idea|light|bright|invention)
🔦 flashlight torch dark (flashlight|torch|dark|light|portable)
🏮 red lantern paper (red lantern|paper|light|china|festival)
🪔 diya lamp lighting (diya|lamp|lighting|india|festival)
📔 notebook cover study (notebook|cover|study|notes|book)
📕 closed book read (closed book|read|book|study|literature)
📖 open book reading (open book|reading|book|study|literature)
📗 green book study (green book|study|book|read|literature)
📘 blue book study (blue book|study|book|read|literature)
📙 orange book study (orange book|study|book|read|literature)
📚 books library study (books|library|study|read|literature)
📓 notebook paper notes (notebook|paper|notes|study|write)
📒 ledger notes paper (ledger|notes|paper|accounting|write)
📃 page curl document (page curl|document|paper|file|note)
📜 scroll ancient history (scroll|ancient|history|paper|document)
📄 page up document (page up|document|paper|file|note)
📰 newspaper press news (newspaper|press|news|media|article)
🗞️ rolled newspaper news (rolled newspaper|news|media|article|press)
📑 bookmark tabs favorite (bookmark|tabs|favorite|save|mark)
🔖 bookmark label save (bookmark|label|save|mark|favorite)
🏷️ label tag sale (label|tag|sale|price|sticker)
💰 money bag cash (money bag|cash|money|bag|rich)
💴 yen banknote japan (yen|banknote|japan|money|currency)
💵 dollar banknote cash (dollar|banknote|cash|money|currency)
💶 euro banknote cash (euro|banknote|cash|money|currency)
💷 pound banknote uk (pound|banknote|uk|money|currency)
💸 money wings payment (money wings|payment|money|cash|fly)
💳 credit card payment (credit card|payment|money|card|pay)
🧾 receipt expenses accounting (receipt|expenses|accounting|bill|paper)
💹 chart increasing yen (chart increasing|yen|money|graph|finance)
💱 currency exchange forex (currency exchange|forex|money|trade|finance)
💲 dollar sign currency (dollar sign|currency|money|symbol|cash)
✉️ envelope letter mail (envelope|letter|mail|email|post)
📧 email inbox mail (email|inbox|mail|message|electronic)
📨 incoming envelope mail (incoming envelope|mail|letter|post|receive)
📩 envelope arrow mail (envelope arrow|mail|send|letter|post)
📤 outbox tray mail (outbox tray|mail|send|post|outgoing)
📥 inbox tray mail (inbox tray|mail|receive|post|incoming)
📦 package box mail (package|box|mail|parcel|delivery)
📫 closed mailbox flag (closed mailbox|flag|mail|post|letter)
📪 closed mailbox down (closed mailbox|down|mail|post|letter)
📬 open mailbox flag (open mailbox|flag|mail|post|letter)
📭 open mailbox down (open mailbox|down|mail|post|letter)
📮 postbox letter box (postbox|letter box|mail|post|letter)
🗳️ ballot box vote (ballot box|vote|election|politics|democracy)
✏️ pencil write stationery (pencil|write|stationery|draw|school)
✒️ nib pen ink (nib pen|ink|write|stationery|calligraphy)
🖋️ fountain pen write (fountain pen|write|stationery|ink|calligraphy)
🖊️ pen writing stationery (pen|writing|stationery|write|ink)
🖌️ paintbrush art drawing (paintbrush|art|drawing|paint|brush)
🖍️ crayon art drawing (crayon|art|drawing|color|wax)
📝 memo note pencil (memo|note|pencil|write|reminder)
💼 briefcase business work (briefcase|business|work|office|bag)
📁 file folder document (file folder|document|office|file|folder)
📂 open file folder (open file folder|file|folder|document|office)
🗂️ card index dividers (card index|dividers|office|file|organize)
📅 calendar date schedule (calendar|date|schedule|plan|time)
📆 tear calendar date (tear calendar|date|schedule|plan|time)
🗒️ spiral notepad memo (spiral notepad|memo|notes|write|office)
🗓️ spiral calendar schedule (spiral calendar|schedule|date|plan|time)
📇 card index business (card index|business|office|contact|file)
📈 chart increasing growth (chart increasing|growth|graph|finance|up)
📉 chart decreasing loss (chart decreasing|loss|graph|finance|down)
📊 bar chart graph (bar chart|graph|data|statistics|finance)
📋 clipboard document notes (clipboard|document|notes|office|list)
📌 pushpin location mark (pushpin|location|mark|pin|office)
📍 round pushpin location (round pushpin|location|mark|pin|map)
📎 paperclip stationery clip (paperclip|stationery|clip|office|attach)
🖇️ linked paperclips clips (linked paperclips|clips|office|attach|paperclip)
📏 straight ruler ruler (straight ruler|ruler|measure|math|stationery)
📐 triangular ruler math (triangular ruler|math|measure|geometry|stationery)
✂️ scissors cut paper (scissors|cut|paper|stationery|tool)
🗃️ card file box (card file|box|office|storage|file)
🗄️ file cabinet storage (file cabinet|storage|office|file|furniture)
🗑️ wastebasket trash bin (wastebasket|trash|bin|delete|garbage)
🔒 locked security lock (locked|security|lock|secure|private)
🔓 unlocked open lock (unlocked|open|lock|security|access)
🔏 locked pen secret (locked pen|secret|privacy|lock|write)
🔐 locked key privacy (locked key|privacy|lock|secure|password)
🔑 key door password (key|door|password|access|unlock)
🗝️ old key vintage (old key|vintage|key|antique|unlock)
🔨 hammer tool build (hammer|tool|build|fix|nail)
🪓 axe tool chop (axe|tool|chop|wood|cut)
⛏️ pickaxe dig tool (pickaxe|dig|tool|mine|craft)
⚒️ hammer pick tools (hammer pick|tools|build|mine|fix)
🛠️ hammer wrench tools (hammer wrench|tools|fix|build|repair)
🗡️ dagger knife weapon (dagger|knife|weapon|blade|stab)
⚔️ crossed swords combat (crossed swords|combat|weapon|fight|battle)
🔫 pistol gun weapon (pistol|gun|weapon|shoot|firearm)
🏹 bow arrow sport (bow|arrow|sport|archery|weapon)
🛡️ shield protection armor (shield|protection|armor|defense|guard)
🔧 wrench tool fix (wrench|tool|fix|repair|spanner)
🔩 nut bolt hardware (nut bolt|hardware|tool|screw|fix)
⚙️ gear cog settings (gear|cog|settings|config|machine)
🗜️ clamp tool fix (clamp|tool|fix|hold|vise)
⚖️ balance scale law (balance|scale|law|justice|weight)
🦯 probing cane blind (probing cane|blind|accessibility|white cane|mobility)
🔗 link chain url (link|chain|url|web|hyperlink)
⛓️ chains lock security (chains|lock|security|bind|metal)
🧰 toolbox tools fix (toolbox|tools|fix|repair|kit)
🧲 magnet attraction attraction (magnet|attraction|magnetic|horseshoe|pull)
⚗️ alembic science chemistry (alembic|science|chemistry|distill|lab)
🧪 test tube lab (test tube|lab|science|chemistry|experiment)
🧫 petri dish bacteria (petri dish|bacteria|science|lab|biology)
🧬 dna genetics biology (dna|genetics|biology|science|helix)
🔬 microscope science lab (microscope|science|lab|biology|magnify)
🔭 telescope space astronomy (telescope|space|astronomy|stars|science)
📡 satellite dish radio (satellite dish|radio|signal|space|antenna)
💉 syringe needle medical (syringe|needle|medical|vaccine|shot)
🩸 drop blood injury (drop blood|injury|blood|medical|donate)
💊 pill medicine drug (pill|medicine|drug|medical|health)
🩹 adhesive bandage heal (adhesive bandage|heal|bandage|medical|injury)
🩺 stethoscope doctor medical (stethoscope|doctor|medical|health|heart)
🚪 door entry exit (door|entry|exit|house|open)
🛏️ bed sleep rest (bed|sleep|rest|furniture|nap)
🛋️ couch sofa lamp (couch|sofa|lamp|furniture|living room)
🪑 chair sit furniture (chair|sit|furniture|seat|stool)
🚽 toilet restroom wc (toilet|restroom|wc|bathroom|loo)
🚿 shower bathroom clean (shower|bathroom|clean|wash|water)
🛁 bathtub bath wash (bathtub|bath|wash|bathroom|water)
🪒 razor shave cut (razor|shave|cut|grooming|blade)
🧴 lotion bottle moisturizer (lotion|bottle|moisturizer|skincare|cream)
🧷 safety pin diaper (safety pin|diaper|baby|pin|clothing)
🧹 broom sweep clean (broom|sweep|clean|housework|witch)
🧺 basket laundry wash (basket|laundry|wash|clothes|housework)
🧻 roll paper tissue (roll paper|tissue|toilet paper|bathroom|clean)
🧼 soap bar cleaning (soap|bar|cleaning|wash|bath)
🧽 sponge wash clean (sponge|wash|clean|bath|scrub)
🧯 fire extinguisher safety (fire extinguisher|safety|fire|emergency|extinguish)
🛒 shopping cart trolley (shopping cart|trolley|shop|groceries|store)
🚬 cigarette smoke tobacco (cigarette|smoke|tobacco|smoking|bad habit)
⚰️ coffin funeral death (coffin|funeral|death|dead|burial)
⚱️ funeral urn ashes (funeral urn|ashes|death|cremation|urn)
🗿 moai statue rock (moai|statue|rock|easter island|stone)
🏧 atm sign cash (atm|bank|cash|money|sign|symbol)
🚮 litter bin sign (bin|litter|sign|symbol|trash|waste)
🚰 potable water tap (drink|potable|tap|water|sign)
♿ wheelchair symbol access (access|disabled|handicap|symbol|wheelchair)
🚹 mens room toilet (mens|room|toilet|wc)
🚺 womens room restroom (restroom|womens|room|toilet|wc)
🚻 restroom wc symbol (restroom|symbol|wc|toilet)
🚼 baby symbol nursery (baby|nursery|symbol)
🚾 water closet wc (closet|water|wc|toilet)
🛂 passport control border (border|control|passport)
🛃 customs control border (border|control|customs)
🛄 baggage claim airport (airport|baggage|claim)
🛅 left luggage storage (left|luggage|storage)
⚠️ warning sign alert (alert|sign|warning)
🚸 children crossing warning (children|crossing|warning)
⛔ no entry stop (entry|no|stop)
🚫 prohibited sign stop (prohibited|sign|stop)
🚳 no bicycles sign (bicycles|no|sign)
🚭 no smoking sign (no|sign|smoking)
🚯 no littering sign (littering|no|sign)
🚱 non potable water (non|potable|water)
🚷 no pedestrians sign (no|pedestrians|sign)
📵 no mobile phones (mobile|no|phones)
🔞 no under eighteen (eighteen|no|under)
☢️ radioactive nuclear danger (danger|nuclear|radioactive)
☣️ biohazard danger sign (biohazard|danger|sign)
⬆️ up arrow direction (arrow|direction|up)
↗️ up right arrow (arrow|right|up)
➡️ right arrow next (arrow|next|right)
↘️ down right arrow (arrow|down|right)
⬇️ down arrow bottom (arrow|bottom|down)
↙️ down left arrow (arrow|down|left)
⬅️ left arrow back (arrow|back|left)
↖️ up left arrow (arrow|left|up)
↕️ up down arrow (arrow|down|up)
↔️ left right arrow (arrow|left|right)
↩️ right arrow curving left (arrow|curving|left|right)
↪️ left arrow curving right (arrow|curving|left|right)
⤴️ arrow curving up (arrow|curving|up)
⤵️ arrow curving down (arrow|curving|down)
🔃 clockwise arrows sync (arrows|clockwise|sync)
🔄 counterclockwise arrows sync (arrows|counterclockwise|sync)
🔙 back arrow return (arrow|back|return)
🔚 end arrow stop (arrow|end|stop)
🔛 on arrow active (active|arrow|on)
🔜 soon arrow coming (arrow|coming|soon)
🔝 top arrow above (above|arrow|top)
🛐 place of worship (place|worship)
⚛️ atom symbol physics (atom|physics|symbol)
🕉️ om hindu symbol (hindu|om|symbol)
✡️ star of david (david|star)
☸️ wheel of dharma (dharma|wheel)
☯️ yin yang balance (balance|yang|yin)
✝️ latin cross christian (christian|cross|latin)
☦️ orthodox cross religion (cross|orthodox|religion)
☪️ star and crescent (crescent|star)
☮️ peace symbol hippie (hippie|peace|symbol)
🕎 menorah hanukkah candles (candles|hanukkah|menorah)
🔯 dotted six pointed star (dotted|pointed|six|star)
♈ aries zodiac sign (aries|sign|zodiac)
♉ taurus zodiac sign (sign|taurus|zodiac)
♊ gemini zodiac sign (gemini|sign|zodiac)
♋ cancer zodiac sign (cancer|sign|zodiac)
♌ leo zodiac sign (leo|sign|zodiac)
♍ virgo zodiac sign (sign|virgo|zodiac)
♎ libra zodiac sign (libra|sign|zodiac)
♏ scorpio zodiac sign (scorpio|sign|zodiac)
♐ sagittarius zodiac sign (sagittarius|sign|zodiac)
♑ capricorn zodiac sign (capricorn|sign|zodiac)
♒ aquarius zodiac sign (aquarius|sign|zodiac)
♓ pisces zodiac sign (pisces|sign|zodiac)
⛎ ophiuchus zodiac sign (ophiuchus|sign|zodiac)
🔀 shuffle button random (button|random|shuffle)
🔁 repeat button loop (button|loop|repeat)
🔂 repeat single loop (loop|repeat|single)
▶️ play button right (button|play|right)
⏩ fast forward button (button|fast|forward)
⏭️ next track button (button|next|track)
⏯️ play pause button (button|pause|play)
◀️ reverse button left (button|left|reverse)
⏪ fast reverse button (button|fast|reverse)
⏮️ last track button (button|last|track)
🔼 upwards button top (button|top|upwards)
⏫ fast up button (button|fast|up)
🔽 downwards button bottom (bottom|button|downwards)
⏬ fast down button (button|down|fast)
⏸️ pause button stop (button|pause|stop)
⏹️ stop button square (button|square|stop)
⏺️ record button circle (button|circle|record)
⏏️ eject button out (button|eject|out)
🎦 cinema theater movie (cinema|movie|theater)
🔅 dim button low (button|dim|low)
🔆 bright button light (bright|button|light)
📶 antenna bars signal (antenna|bars|signal)
📳 vibration mode phone (mode|phone|vibration)
📴 mobile phone off (mobile|off|phone)
♀️ female sign woman (female|sign|woman)
♂️ male sign man (male|man|sign)
⚕️ medical symbol health (health|medical|symbol)
♾️ infinity symbol forever (forever|infinity|symbol)
♻️ recycling symbol green (green|recycling|symbol)
⚜️ fleur de lis (fleur|lis)
🔱 trident emblem spear (emblem|spear|trident)
📛 name badge tag (badge|name|tag)
🔰 beginner badge shield (badge|beginner|shield)
⭕ hollow red circle (circle|hollow|red)
✅ check mark green (check|green|mark)
☑️ check box tick (box|check|tick)
✔️ check mark tick (check|mark|tick)
✖️ multiplication sign math (math|multiplication|sign)
❌ cross mark cancel (cancel|cross|mark)
❎ cross mark button (button|cross|mark)
➕ plus sign add (add|plus|sign)
➖ minus sign subtract (minus|sign|subtract)
➗ division sign divide (divide|division|sign)
➰ curly loop scribble (curly|loop|scribble)
➿ double curly loop (curly|double|loop)
〽️ part alternation mark (alternation|mark|part)
✳️ eight spoked asterisk (asterisk|eight|spoked)
✴️ eight pointed star (eight|pointed|star)
❇️ sparkle star green (green|sparkle|star)
‼️ double exclamation mark (double|exclamation|mark)
⁉️ exclamation question mark (exclamation|mark|question)
❓ question mark doubt (doubt|mark|question)
❔ white question mark (mark|question|white)
❕ white exclamation mark (exclamation|mark|white)
❗ exclamation mark danger (danger|exclamation|mark)
〰️ wavy dash line (dash|line|wavy)
©️ copyright mark legal (copyright|legal|mark)
®️ registered trademark (registered|trademark)
™️ trademark brand (brand|trademark)
#️⃣ keycap hash symbol (hash|keycap|symbol)
*️⃣ keycap star symbol (keycap|star|symbol)
0️⃣ keycap zero number (keycap|number|zero)
1️⃣ keycap one number (keycap|number|one)
2️⃣ keycap two number (keycap|number|two)
3️⃣ keycap three number (keycap|number|three)
4️⃣ keycap four number (keycap|number|four)
5️⃣ keycap five number (keycap|number|five)
6️⃣ keycap six number (keycap|number|six)
7️⃣ keycap seven number (keycap|number|seven)
8️⃣ keycap eight number (keycap|number|eight)
9️⃣ keycap nine number (keycap|number|nine)
🔟 keycap ten number (keycap|number|ten)
🔠 input uppercase latin (input|latin|uppercase)
🔡 input lowercase latin (input|latin|lowercase)
🔢 input numbers symbol (input|numbers|symbol)
🔣 input symbols glyphs (glyphs|input|symbols)
🔤 input latin letters (input|latin|letters)
🅰️ a button red (button|red|a)
🆎 ab button red (ab|button|red)
🅱️ b button red (b|button|red)
🆑 cl button clear (button|clear|cl)
🆒 cool button text (button|cool|text)
🆓 free button text (button|free|text)
ℹ️ info button blue (blue|button|info)
🆔 id button purple (button|id|purple)
Ⓜ️ circled m transit (circled|m|transit)
🆕 new button start (button|new|start)
🆖 ng button no-good (button|no-good|ng)
🅾️ o button red (button|o|red)
🆗 ok button agree (agree|button|ok)
🅿️ parking sign blue (blue|parking|sign)
🆘 sos button emergency (button|emergency|sos)
🆙 up button text (button|text|up)
🆚 vs button versus (button|versus|vs)
🈁 japanese here button (button|here|japanese)
🈂️ japanese service charge (charge|japanese|service)
🈷️ japanese monthly amount (amount|japanese|monthly)
🈶 japanese not free (free|japanese|not)
🈯 japanese reserved sign (japanese|reserved|sign)
🉐 japanese bargain button (bargain|button|japanese)
🈹 japanese discount button (button|discount|japanese)
🈚 japanese free charge (charge|free|japanese)
🈲 japanese prohibited sign (japanese|prohibited|sign)
🉑 japanese acceptable button (acceptable|button|japanese)
🈸 japanese application sign (application|japanese|sign)
🈴 japanese passing grade (grade|japanese|passing)
🈳 japanese vacancy sign (japanese|sign|vacancy)
㊗️ japanese congratulations button (button|congratulations|japanese)
㊙️ japanese secret sign (japanese|secret|sign)
🈺 japanese open business (business|japanese|open)
🈵 japanese no vacancy (japanese|no|vacancy)
🔴 red circle button (button|circle|red)
🟠 orange circle button (button|circle|orange)
🟡 yellow circle button (button|circle|yellow)
🟢 green circle button (button|circle|green)
🔵 blue circle button (button|blue|circle)
🟣 purple circle button (button|circle|purple)
🟤 brown circle button (brown|button|circle)
⚫ black circle button (black|button|circle)
⚪ white circle button (button|circle|white)
🟥 red square block (block|red|square)
🟧 orange square block (block|orange|square)
🟨 yellow square block (block|square|yellow)
🟩 green square block (block|green|square)
🟦 blue square block (block|blue|square)
🟪 purple square block (block|purple|square)
🟫 brown square block (block|brown|square)
⬛ black large square (black|large|square)
⬜ white large square (large|square|white)
◼️ black medium square (black|medium|square)
◻️ white medium square (medium|square|white)
◾ black small square (black|small|square)
◽ white small square (small|square|white)
▪️ black tiny square (black|square|tiny)
▫️ white tiny square (square|tiny|white)
🔶 large orange diamond (diamond|large|orange)
🔷 large blue diamond (blue|diamond|large)
🔸 small orange diamond (diamond|orange|small)
🔹 small blue diamond (blue|diamond|small)
🔺 red triangle up (red|triangle|up)
🔻 red triangle down (down|red|triangle)
💠 diamond with dot (diamond|dot)
🔘 radio button input (button|input|radio)
🔳 white square button (button|square|white)
🔲 black square button (black|button|square)
🏁 chequered flag race finish (checkered|chequered|finish|flag|race|racing)
🚩 triangular flag post mark (flag|mark|post|triangular|triangle)
🎌 crossed flags japan (cross|crossed|flag|flags|japan|japanese)
🏴 black flag pirate (black|flag|pirate)
🏳️ white flag surrender (flag|surrender|white)
🏳️‍🌈 rainbow flag pride lgbt (flag|lgbt|pride|rainbow)
🏴‍☠️ pirate flag skull crossbones (crossbones|flag|pirate|skull)
🇦🇨 flag ascension island (ac|ascension|country|flag|island|nation|national)
🇦🇩 flag andorra (ad|andorra|country|flag|nation|national)
🇦🇪 flag uae united arab emirates (ae|arab|country|emirates|flag|nation|national|uae|united)
🇦🇫 flag afghanistan (af|afghanistan|country|flag|nation|national)
🇦🇬 flag antigua barbuda (ag|antigua|barbuda|country|flag|nation|national)
🇦🇮 flag anguilla (ai|anguilla|country|flag|nation|national)
🇦🇱 flag albania (al|albania|country|flag|nation|national)
🇦🇲 flag armenia (am|armenia|country|flag|nation|national)
🇦🇴 flag angola (ao|angola|country|flag|nation|national)
🇦🇶 flag antarctica (aq|antarctica|country|flag|nation|national)
🇦🇷 flag argentina (ar|argentina|country|flag|nation|national)
🇦🇸 flag american samoa (as|american|country|flag|nation|national|samoa)
🇦🇹 flag austria (at|austria|country|flag|nation|national)
🇦🇺 flag australia (au|australia|country|flag|nation|national)
🇦🇼 flag aruba (aw|aruba|country|flag|nation|national)
🇦🇽 flag aland islands (ax|aland|country|flag|islands|nation|national)
🇦🇿 flag azerbaijan (az|azerbaijan|country|flag|nation|national)
🇧🇦 flag bosnia herzegovina (ba|bosnia|country|flag|herzegovina|nation|national)
🇧🇧 flag barbados (bb|barbados|country|flag|nation|national)
🇧🇩 flag bangladesh (bd|bangladesh|country|flag|nation|national)
🇧🇪 flag belgium (be|belgium|country|flag|nation|national)
🇧🇫 flag burkina faso (bf|burkina|country|faso|flag|nation|national)
🇧🇬 flag bulgaria (bg|bulgaria|country|flag|nation|national)
🇧🇭 flag bahrain (bh|bahrain|country|flag|nation|national)
🇧🇮 flag burundi (bi|burundi|country|flag|nation|national)
🇧🇯 flag benin (bj|benin|country|flag|nation|national)
🇧🇱 flag st barthelemy (bl|barthelemy|country|flag|nation|national|st)
🇧🇲 flag bermuda (bm|bermuda|country|flag|nation|national)
🇧🇳 flag brunei (bn|brunei|country|flag|nation|national)
🇧🇴 flag bolivia (bo|bolivia|country|flag|nation|national)
🇧🇶 flag caribbean netherlands (bq|caribbean|country|flag|nation|national|netherlands)
🇧🇷 flag brazil (br|brazil|country|flag|nation|national)
🇧🇸 flag bahamas (bs|bahamas|country|flag|nation|national)
🇧🇹 flag bhutan (bt|bhutan|country|flag|nation|national)
🇧🇻 flag bouvet island (bv|bouvet|country|flag|island|nation|national)
🇧🇼 flag botswana (bw|botswana|country|flag|nation|national)
🇧🇾 flag belarus (by|belarus|country|flag|nation|national)
🇧🇿 flag belize (bz|belize|country|flag|nation|national)
🇨🇦 flag canada (ca|canada|country|flag|nation|national)
🇨🇨 flag cocos islands (cc|cocos|country|flag|islands|nation|national)
🇨🇩 flag congo kinshasa (cd|congo|country|flag|kinshasa|nation|national)
🇨🇫 flag central african republic (cf|african|central|country|flag|nation|national|republic)
🇨🇬 flag congo brazzaville (cg|brazzaville|congo|country|flag|nation|national)
🇨🇭 flag switzerland (ch|country|flag|nation|national|switzerland)
🇨🇮 flag cote divoire (ci|cote|country|divoire|flag|nation|national)
🇨🇰 flag cook islands (ck|cook|country|flag|islands|nation|national)
🇨🇱 flag chile (cl|chile|country|flag|nation|national)
🇨🇲 flag cameroon (cm|cameroon|country|flag|nation|national)
🇨🇳 flag china (cn|china|country|flag|nation|national)
🇨🇴 flag colombia (co|colombia|country|flag|nation|national)
🇨🇵 flag clipperton island (cp|clipperton|country|flag|island|nation|national)
🇨🇷 flag costa rica (cr|costa|country|flag|nation|national|rica)
🇨🇺 flag cuba (cu|cuba|country|flag|nation|national)
🇨🇻 flag cape verde (cv|cape|country|flag|nation|national|verde)
🇨🇼 flag curacao (cw|country|curacao|flag|nation|national)
🇨🇽 flag christmas island (cx|christmas|country|flag|island|nation|national)
🇨🇾 flag cyprus (cy|country|cyprus|flag|nation|national)
🇨🇿 flag czechia (cz|czechia|country|flag|nation|national)
🇩🇪 flag germany (de|country|flag|germany|nation|national)
🇩🇬 flag diego garcia (dg|country|diego|flag|garcia|nation|national)
🇩🇯 flag djibouti (dj|country|djibouti|flag|nation|national)
🇩🇰 flag denmark (dk|denmark|country|flag|nation|national)
🇩🇲 flag dominica (dm|country|dominica|flag|nation|national)
🇩🇴 flag dominican republic (do|country|dominican|flag|nation|national|republic)
🇩🇿 flag algeria (dz|algeria|country|flag|nation|national)
🇪🇦 flag ceuta melilla (ea|ceuta|country|flag|melilla|nation|national)
🇪🇨 flag ecuador (ec|country|ecuador|flag|nation|national)
🇪🇪 flag estonia (ee|country|estonia|flag|nation|national)
🇪🇬 flag egypt (eg|country|egypt|flag|nation|national)
🇪🇭 flag western sahara (eh|country|flag|nation|national|sahara|western)
🇪🇷 flag eritrea (er|country|eritrea|flag|nation|national)
🇪🇸 flag spain (es|country|flag|nation|national|spain)
🇪🇹 flag ethiopia (et|country|ethiopia|flag|nation|national)
🇪🇺 flag european union (eu|country|european|flag|nation|national|union)
🇫🇮 flag finland (fi|country|finland|flag|nation|national)
🇫🇯 flag fiji (fj|country|fiji|flag|nation|national)
🇫🇰 flag falkland islands (fk|country|falkland|flag|islands|nation|national)
🇫🇲 flag micronesia (fm|country|flag|micronesia|nation|national)
🇫🇴 flag faroe islands (fo|country|faroe|flag|islands|nation|national)
🇫🇷 flag france (fr|country|flag|france|nation|national)
🇬🇦 flag gabon (ga|country|flag|gabon|nation|national)
🇬🇧 flag uk united kingdom (gb|britain|country|england|flag|kingdom|nation|national|uk|united)
🇬🇩 flag grenada (gd|country|flag|grenada|nation|national)
🇬🇪 flag georgia (ge|country|flag|georgia|nation|national)
🇬🇫 flag french guiana (gf|country|flag|french|guiana|nation|national)
🇬🇬 flag guernsey (gg|country|flag|guernsey|nation|national)
🇬🇭 flag ghana (gh|country|flag|ghana|nation|national)
🇬🇮 flag gibraltar (gi|country|flag|gibraltar|nation|national)
🇬🇱 flag greenland (gl|country|flag|greenland|nation|national)
🇬🇲 flag gambia (gm|country|flag|gambia|nation|national)
🇬🇳 flag guinea (gn|country|flag|guinea|nation|national)
🇬🇵 flag guadeloupe (gp|country|flag|guadeloupe|nation|national)
🇬🇶 flag equatorial guinea (gq|country|equatorial|flag|guinea|nation|national)
🇬🇷 flag greece (gr|country|flag|greece|nation|national)
🇬🇸 flag south georgia (gs|country|flag|georgia|nation|national|south)
🇬🇹 flag guatemala (gt|country|flag|guatemala|nation|national)
🇬🇺 flag guam (gu|country|flag|guam|nation|national)
🇬🇼 flag guinea bissau (gw|bissau|country|flag|guinea|nation|national)
🇬🇾 flag guyana (gy|country|flag|guyana|nation|national)
🇭🇰 flag hong kong (hk|country|flag|hong|kong|nation|national)
🇭🇲 flag heard mcdonald islands (hm|country|flag|heard|islands|mcdonald|nation|national)
🇭🇳 flag honduras (hn|country|flag|honduras|nation|national)
🇭🇷 flag croatia (hr|country|croatia|flag|nation|national)
🇭🇹 flag haiti (ht|country|flag|haiti|nation|national)
🇭🇺 flag hungary (hu|country|flag|hungary|nation|national)
🇮🇨 flag canary islands (ic|canary|country|flag|islands|nation|national)
🇮🇩 flag indonesia (id|country|flag|indonesia|nation|national)
🇮🇪 flag ireland (ie|country|flag|ireland|nation|national)
🇮🇱 flag israel (il|country|flag|israel|nation|national)
🇮🇲 flag isle of man (im|country|flag|isle|man|nation|national)
🇮🇳 flag india (in|country|flag|india|nation|national)
🇮🇴 flag british indian ocean territory (io|british|country|flag|indian|nation|national|ocean|territory)
🇮🇶 flag iraq (iq|country|flag|iraq|nation|national)
🇮🇷 flag iran (ir|country|flag|iran|nation|national)
🇮🇸 flag iceland (is|country|flag|iceland|nation|national)
🇮🇹 flag italy (it|country|flag|italy|nation|national)
🇯🇪 flag jersey (je|country|flag|jersey|nation|national)
🇯🇲 flag jamaica (jm|country|flag|jamaica|nation|national)
🇯🇴 flag jordan (jo|country|flag|jordan|nation|national)
🇯🇵 flag japan (jp|country|flag|japan|nation|national)
🇰🇪 flag kenya (ke|country|flag|kenya|nation|national)
🇰🇬 flag kyrgyzstan (kg|country|flag|kyrgyzstan|nation|national)
🇰🇭 flag cambodia (kh|cambodia|country|flag|nation|national)
🇰🇮 flag kiribati (ki|country|flag|kiribati|nation|national)
🇰🇲 flag comoros (km|comoros|country|flag|nation|national)
🇰🇳 flag st kitts nevis (kn|country|flag|kitts|nation|national|nevis|st)
🇰🇵 flag north korea (kp|country|flag|korea|nation|national|north)
🇰🇷 flag south korea (kr|country|flag|korea|nation|national|south)
🇰🇼 flag kuwait (kw|country|flag|kuwait|nation|national)
🇰🇾 flag cayman islands (ky|cayman|country|flag|islands|nation|national)
🇰🇿 flag kazakhstan (kz|country|flag|kazakhstan|nation|national)
🇱🇦 flag laos (la|country|flag|laos|nation|national)
🇱🇧 flag lebanon (lb|country|flag|lebanon|nation|national)
🇱🇨 flag st lucia (lc|country|flag|lucia|nation|national|st)
🇱🇮 flag liechtenstein (li|country|flag|liechtenstein|nation|national)
🇱🇰 flag sri lanka (lk|country|flag|lanka|nation|national|sri)
🇱🇷 flag liberia (lr|country|flag|liberia|nation|national)
🇱🇸 flag lesotho (ls|country|flag|lesotho|nation|national)
🇱🇹 flag lithuania (lt|country|flag|lithuania|nation|national)
🇱🇺 flag luxembourg (lu|country|flag|luxembourg|nation|national)
🇱🇻 flag latvia (lv|country|flag|latvia|nation|national)
🇱🇾 flag libya (ly|country|flag|libya|nation|national)
🇲🇦 flag morocco (ma|country|flag|morocco|nation|national)
🇲🇨 flag monaco (mc|country|flag|monaco|nation|national)
🇲🇩 flag moldova (md|country|flag|moldova|nation|national)
🇲🇪 flag montenegro (me|country|flag|montenegro|nation|national)
🇲🇫 flag st martin (mf|country|flag|martin|nation|national|st)
🇲🇬 flag madagascar (mg|country|flag|madagascar|nation|national)
🇲🇭 flag marshall islands (mh|country|flag|islands|marshall|nation|national)
🇲🇰 flag north macedonia (mk|country|flag|macedonia|nation|national|north)
🇲🇱 flag mali (ml|country|flag|mali|nation|national)
🇲🇲 flag myanmar (mm|country|flag|myanmar|nation|national)
🇲🇳 flag mongolia (mn|country|flag|mongolia|nation|national)
🇲🇴 flag macao (mo|country|flag|macao|nation|national)
🇲🇵 flag northern mariana islands (mp|country|flag|islands|mariana|nation|national|northern)
🇲🇶 flag martinique (mq|country|flag|martinique|nation|national)
🇲🇷 flag mauritania (mr|country|flag|mauritania|nation|national)
🇲🇸 flag montserrat (ms|country|flag|montserrat|nation|national)
🇲🇹 flag malta (mt|country|flag|malta|nation|national)
🇲🇺 flag mauritius (mu|country|flag|mauritius|nation|national)
🇲🇻 flag maldives (mv|country|flag|maldives|nation|national)
🇲🇼 flag malawi (mw|country|flag|malawi|nation|national)
🇲🇽 flag mexico (mx|country|flag|mexico|nation|national)
🇲🇾 flag malaysia (my|country|flag|malaysia|nation|national)
🇲🇿 flag mozambique (mz|country|flag|mozambique|nation|national)
🇳🇦 flag namibia (na|country|flag|namibia|nation|national)
🇳🇨 flag new caledonia (nc|caledonia|country|flag|nation|national|new)
🇳🇪 flag niger (ne|country|flag|nation|national|niger)
🇳🇫 flag norfolk island (nf|country|flag|island|nation|national|norfolk)
🇳🇬 flag nigeria (ng|country|flag|nation|national|nigeria)
🇳🇮 flag nicaragua (ni|country|flag|nation|national|nicaragua)
🇳🇱 flag netherlands (nl|country|flag|nation|national|netherlands)
🇳🇴 flag norway (no|country|flag|nation|national|norway)
🇳🇵 flag nepal (np|country|flag|nation|national|nepal)
🇳🇷 flag nauru (nr|country|flag|nation|national|nauru)
🇳🇺 flag niue (nu|country|flag|nation|national|niue)
🇳🇿 flag new zealand (nz|country|flag|nation|national|new|zealand)
🇴🇲 flag oman (om|country|flag|nation|national|oman)
🇵🇦 flag panama (pa|country|flag|nation|national|panama)
🇵🇪 flag peru (pe|country|flag|nation|national|peru)
🇵🇫 flag french polynesia (pf|country|flag|french|nation|national|polynesia)
🇵🇬 flag papua new guinea (pg|country|flag|guinea|nation|national|new|papua)
🇵🇭 flag philippines (ph|country|flag|nation|national|philippines)
🇵🇰 flag pakistan (pk|country|flag|nation|national|pakistan)
🇵🇱 flag poland (pl|country|flag|nation|national|poland)
🇵🇲 flag st pierre miquelon (pm|country|flag|miquelon|nation|national|pierre|st)
🇵🇳 flag pitcairn islands (pn|country|flag|islands|nation|national|pitcairn)
🇵🇷 flag puerto rico (pr|country|flag|nation|national|puerto|rico)
🇵🇸 flag palestine (ps|country|flag|nation|national|palestine)
🇵🇹 flag portugal (pt|country|flag|nation|national|portugal)
🇵🇼 flag palau (pw|country|flag|nation|national|palau)
🇵🇾 flag paraguay (py|country|flag|nation|national|paraguay)
🇶🇦 flag qatar (qa|country|flag|nation|national|qatar)
🇷🇪 flag reunion (re|country|flag|nation|national|reunion)
🇷🇴 flag romania (ro|country|flag|nation|national|romania)
🇷🇸 flag serbia (rs|country|flag|nation|national|serbia)
🇷🇺 flag russia (ru|country|flag|nation|national|russia)
🇷🇼 flag rwanda (rw|country|flag|nation|national|rwanda)
🇸🇦 flag saudi arabia (sa|country|flag|nation|national|saudi|arabia)
🇸🇧 flag solomon islands (sb|country|flag|nation|national|solomon|islands)
🇸🇨 flag seychelles (sc|country|flag|nation|national|seychelles)
🇸🇩 flag sudan (sd|country|flag|nation|national|sudan)
🇸🇪 flag sweden (se|country|flag|nation|national|sweden)
🇸🇬 flag singapore (sg|country|flag|nation|national|singapore)
🇸🇭 flag st helena (sh|country|flag|nation|national|st|helena)
🇸🇮 flag slovenia (si|country|flag|nation|national|slovenia)
🇸🇯 flag svalbard jan mayen (sj|country|flag|nation|national|svalbard|jan|mayen)
🇸🇰 flag slovakia (sk|country|flag|nation|national|slovakia)
🇸🇱 flag sierra leone (sl|country|flag|nation|national|sierra|leone)
🇸🇲 flag san marino (sm|country|flag|nation|national|san|marino)
🇸🇳 flag senegal (sn|country|flag|nation|national|senegal)
🇸🇴 flag somalia (so|country|flag|nation|national|somalia)
🇸🇷 flag suriname (sr|country|flag|nation|national|suriname)
🇸🇸 flag south sudan (ss|country|flag|nation|national|south|sudan)
🇸🇹 flag sao tome principe (st|country|flag|nation|national|sao|tome|principe)
🇸🇻 flag el salvador (sv|country|flag|nation|national|el|salvador)
🇸🇽 flag sint maarten (sx|country|flag|nation|national|sint|maarten)
🇸🇾 flag syria (sy|country|flag|nation|national|syria)
🇸🇿 flag eswatini (sz|country|flag|nation|national|eswatini)
🇹🇦 flag tristan da cunha (ta|country|flag|nation|national|tristan|da|cunha)
🇹🇨 flag turks caicos (tc|country|flag|nation|national|turks|caicos)
🇹🇩 flag chad (td|country|flag|nation|national|chad)
🇹🇫 flag french southern territories (tf|country|flag|nation|national|french|southern|territories)
🇹🇬 flag togo (tg|country|flag|nation|national|togo)
🇹🇭 flag thailand (th|country|flag|nation|national|thailand)
🇹🇯 flag tajikistan (tj|country|flag|nation|national|tajikistan)
🇹🇰 flag tokelau (tk|country|flag|nation|national|tokelau)
🇹🇱 flag timor leste (tl|country|flag|nation|national|timor|leste)
🇹🇲 flag turkmenistan (tm|country|flag|nation|national|turkmenistan)
🇹🇳 flag tunisia (tn|country|flag|nation|national|tunisia)
🇹🇴 flag tonga (to|country|flag|nation|national|tonga)
🇹🇷 flag turkey (tr|country|flag|nation|national|turkey)
🇹🇹 flag trinidad tobago (tt|country|flag|nation|national|trinidad|tobago)
🇹🇻 flag tuvalu (tv|country|flag|nation|national|tuvalu)
🇹🇼 flag taiwan (tw|country|flag|nation|national|taiwan)
🇹🇿 flag tanzania (tz|country|flag|nation|national|tanzania)
🇺🇦 flag ukraine (ua|country|flag|nation|national|ukraine)
🇺🇬 flag uganda (ug|country|flag|nation|national|uganda)
🇺🇲 flag us outlying islands (um|country|flag|nation|national|us|outlying|islands)
🇺🇳 flag united nations (un|international|organization|global|united|nations)
🇺🇸 flag usa united states (us|country|flag|nation|national|usa|united|states|america)
🇺🇾 flag uruguay (uy|country|flag|nation|national|uruguay)
🇺🇿 flag uzbekistan (uz|country|flag|nation|national|uzbekistan)
🇻🇦 flag vatican city (va|country|flag|nation|national|vatican|city)
🇻🇨 flag st vincent grenadines (vc|country|flag|nation|national|st|vincent|grenadines)
🇻🇪 flag venezuela (ve|country|flag|nation|national|venezuela)
🇻🇬 flag british virgin islands (vg|country|flag|nation|national|british|virgin|islands)
🇻🇮 flag us virgin islands (vi|country|flag|nation|national|us|virgin|islands)
🇻🇳 flag vietnam (vn|country|flag|nation|national|vietnam)
🇻🇺 flag vanuatu (vu|country|flag|nation|national|vanuatu)
🇼🇫 flag wallis futuna (wf|country|flag|nation|national|wallis|futuna)
🇼🇸 flag samoa (ws|country|flag|nation|national|samoa)
🇽🇰 flag kosovo (xk|country|flag|nation|national|kosovo)
🇾🇪 flag yemen (ye|country|flag|nation|national|yemen)
🇾🇹 flag mayotte (yt|country|flag|nation|national|mayotte)
🇿🇦 flag south africa (za|country|flag|nation|national|south|africa)
🇿🇲 flag zambia (zm|country|flag|nation|national|zambia)
🇿🇼 flag zimbabwe (zw|country|flag|nation|national|zimbabwe)
🏴󠁧󠁢󠁥󠁮󠁧󠁿 flag england (gb|eng|uk|country|britain|england)
🏴󠁧󠁢󠁳󠁣󠁴󠁿 flag scotland (gb|sct|uk|country|britain|scotland)
🏴󠁧󠁢󠁷󠁬󠁳󠁿 flag wales (gb|wls|uk|country|britain|wales)
🥲 smiling face tear sad (smiling|face|tear|sad|happy|crying|bittersweet|relief)
🥸 disguised face glasses mustache (disguised|face|glasses|mustache|incognito|spy|undercover)
🤌 pinched fingers Italian gesture (pinched|fingers|italian|gesture|hand|sign|capiche)
🫀 anatomical heart organ (anatomical|heart|organ|cardiovascular|biology|medical)
🫁 lungs organ breathe (lungs|organ|breathe|respiratory|breathing|medical|air)
🥷 ninja warrior shadow (ninja|warrior|shadow|assassin|stealth|fighter)
🤵‍♂️ man tuxedo formal (man|tuxedo|formal|groom|suit|wedding)
🤵‍♀️ woman tuxedo formal (woman|tuxedo|formal|suit|bride|groom|wedding)
👰‍♂️ man veil wedding (man|veil|wedding|groom|marriage|husband)
👰‍♀️ woman veil wedding (woman|veil|wedding|bride|marriage|wife)
👩‍🍼 woman feeding baby (woman|feeding|baby|nursing|mother|bottle|milk)
👨‍🍼 man feeding baby (man|feeding|baby|nursing|father|bottle|milk)
🧑‍🍼 person feeding baby (person|feeding|baby|nursing|parent|bottle|milk)
🧑‍🎄 mx claus christmas (mx|claus|christmas|santa|holiday|winter|xmas)
🫂 people hugging hug (people|hugging|hug|embrace|comfort|care|love)
🐈‍⬛ black cat superstition (black|cat|superstition|feline|pet|unlucky|animal)
🦬 bison buffalo animal (bison|buffalo|animal|mammal|wildlife|american)
🦣 mammoth extinct elephant (mammoth|extinct|elephant|prehistoric|ice|age)
🦫 beaver rodent dam (beaver|rodent|dam|animal|timber|wood)
🐻‍❄️ polar bear arctic (polar|bear|arctic|ice|snow|animal)
🦤 dodo extinct bird (dodo|extinct|bird|flightless|animal)
🪶 feather bird plume (feather|bird|plume|flight|write|quill)
🦭 seal sea mammal (seal|sea|mammal|ocean|aquatic|pup)
🪲 beetle bug insect (beetle|bug|insect|pest|scarab)
🪳 cockroach pest insect (cockroach|pest|insect|bug|roach)
🪰 fly insect pest (fly|insect|pest|bug|housefly)
🪱 worm earthworm pest (worm|earthworm|pest|garden|soil)
🪴 potted plant houseplant (potted|plant|houseplant|flower|pot|botany)
🫐 blueberries fruit berry (blueberries|fruit|berry|food|sweet|healthy)
🫒 olive fruit oil (olive|fruit|oil|food|martini|greek)
🫑 bell pepper vegetable (bell|pepper|vegetable|capsicum|food|sweet)
🫓 flatbread pita naan (flatbread|pita|naan|food|bread|tortilla)
🫔 tamale mexican food (tamale|mexican|food|corn|husk)
🫕 fondue melted cheese (fondue|melted|cheese|food|pot|dip)
🫖 teapot tea kettle (teapot|tea|kettle|hot|drink)
🧋 bubble tea boba (bubble|tea|boba|drink|milk|tapioca)
🪨 rock stone boulder (rock|stone|boulder|mineral|geology)
🪵 wood log timber (wood|log|timber|lumber|forest|trunk)
🛖 hut cabin structure (hut|cabin|structure|house|home|tribal)
🛻 pickup truck ute (pickup|truck|ute|vehicle|automobile)
🛼 roller skate derby (roller|skate|derby|sport|footwear)
🪄 magic wand spell (magic|wand|spell|wizard|witch)
🪅 pinata candy party (pinata|candy|party|celebration|birthday)
🪆 nesting dolls matryoshka (nesting|dolls|matryoshka|russian|toy)
🪡 sewing needle thread (sewing|needle|thread|tailor|craft)
🪢 knot rope tied (knot|rope|tied|cord|string)
🩴 thong sandal flip-flop (thong|sandal|flip-flop|footwear|summer)
🪖 military helmet army (military|helmet|army|soldier|war)
🪗 accordion instrument music (accordion|instrument|music|squeeze|box)
🪘 long drum percussion (long|drum|percussion|instrument|music)
🪙 coin money currency (coin|money|currency|gold|cash)
🪃 boomerang weapon throw (boomerang|weapon|throw|australian|curved)
🪚 carpentry saw tool (carpentry|saw|tool|wood|cutting)
🪛 screwdriver tool fix (screwdriver|tool|fix|screw|hardware)
🪝 hook tool catch (hook|tool|catch|pirate|hanger)
🪜 ladder climb tool (ladder|climb|tool|steps|height)
🛗 elevator lift transport (elevator|lift|transport|building|floor)
🪞 mirror reflection vanity (mirror|reflection|vanity|glass|look)
🪟 window glass frame (window|glass|frame|view|house)
🪠 plunger toilet tool (plunger|toilet|tool|bathroom|unclog)
🪤 mouse trap rodent (mouse|trap|rodent|pest|catch)
🪣 bucket pail water (bucket|pail|water|container)
🪥 toothbrush dental hygiene (toothbrush|dental|hygiene|teeth|brush)
🪦 headstone tombstone grave (headstone|tombstone|grave|death|cemetery)
🪧 placard sign protest (placard|sign|protest|march|banner)
⚧️ transgender symbol (transgender|symbol|gender|pride|lgbtq)
🏳️‍⚧️ transgender flag (transgender|flag|pride|lgbtq|blue|pink|white)
🏳️‍🌈 rainbow flag (rainbow|flag|gay|pride|lgbtq|queer)
😶‍🌫️ face clouds foggy (face|clouds|foggy|smoke|haze|fog)
😮‍💨 face exhaling sigh (face|exhaling|sigh|relief|breath|puff)
😵‍💫 face spiral eyes dizzy (face|spiral|eyes|dizzy|confused|hypnotized)
❤️‍🔥 heart fire passionate (heart|fire|passionate|love|burning|hot)
❤️‍🩹 mending heart healing (mending|heart|healing|recovering|bandage|hurt)
🧔‍♂️ man beard facial hair (man|beard|facial|hair|guy)
🧔‍♀️ woman beard facial hair (woman|beard|facial|hair|lady)
🫠 melting face hot melt (melting|face|hot|melt|heat|dissolving)
🫢 face hand over mouth shock (face|hand|over|mouth|shock|gasp|oops)
🫣 face peeking eye scared (face|peeking|eye|scared|shy|hiding|peekaboo)
🫡 saluting face respect (saluting|face|respect|yes|sir|salute)
🫥 dotted line face invisible (dotted|line|face|invisible|hiding|vanishing)
🫤 face diagonal mouth skeptic (face|diagonal|mouth|skeptic|unsure|doubt)
🥹 face holding back tears touched (face|holding|back|tears|touched|emotional|gratitude)
🫱 rightwards hand reach (rightwards|hand|reach|gesture|push)
🫲 leftwards hand reach (leftwards|hand|reach|gesture|shake)
🫳 palm down hand drop (palm|down|hand|drop|shoo|lower)
🫴 palm up hand offer (palm|up|hand|offer|come|here|lift)
🫰 hand index thumb crossed heart (hand|index|thumb|crossed|heart|love|money|expensive)
🫵 index pointing viewer you (index|pointing|viewer|you|point|finger)
🫶 heart hands love support (heart|hands|love|support|care)
🫦 biting lip flirt sexy (biting|lip|flirt|sexy|nervous|anxious)
🫅 person crown monarch (person|crown|monarch|royalty|king|queen)
🫃 pregnant man belly (pregnant|man|belly|expecting|father)
🫄 pregnant person belly (pregnant|person|belly|expecting|parent)
🧌 troll monster creature (troll|monster|creature|fantasy|ogre)
🪸 coral reef ocean (coral|reef|ocean|sea|marine)
🪷 lotus flower bloom (lotus|flower|bloom|plant|water)
🪹 empty nest bird (empty|nest|bird|home)
🪺 nest eggs bird (nest|eggs|bird|spring|birth)
🫘 beans legumes food (beans|legumes|food|seed|pinto)
🫗 pouring liquid spill (pouring|liquid|spill|water|drink)
🫙 jar glass container (jar|glass|container|empty|storage)
🛝 playground slide fun (playground|slide|fun|park|children)
🛞 wheel tire car (wheel|tire|car|vehicle|rubber)
🛟 ring buoy lifebuoy (ring|buoy|lifebuoy|safety|rescue|ocean)
🪬 hamsa protection amulet (hamsa|protection|amulet|hand|evil|eye)
🪩 mirror ball disco (mirror|ball|disco|party|dance|glitter)
🪫 low battery empty (low|battery|empty|power|phone)
🩼 crutch mobility aid (crutch|mobility|aid|medical|injury|hospital)
🩻 xray skeleton medical (xray|skeleton|medical|bone|scan)
🫧 bubbles soap foam (bubbles|soap|foam|water|clean)
🪪 identification card id (identification|card|id|badge|license)
🟰 heavy equals sign math (heavy|equals|sign|math|symbol)
🫯 fight cloud (fight|cloud|cartoon|comic|dust|brawl)
🧑‍🩰 ballet dancer (ballet|dancer|dance|person|performance)
🫍 orca (orca|killer|whale|ocean|sea|animal)
🫈 hairy creature (hairy|creature|bigfoot|sasquatch|cryptid|monster)
🪊 trombone (trombone|instrument|music|brass|band)
🛘 landslide (landslide|disaster|mountain|rock|earth)
🪎 treasure chest (treasure|chest|box|gold|pirate)
