# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e7e0e8"

# Title color for boxes
theme[title]="#d4bbfc"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cdc2db"

# Background color of selected item in processes box
theme[selected_bg]="#d4bbfc"

# Foreground color of selected item in processes box
theme[selected_fg]="#39255c"

# Color of inactive/disabled text
theme[inactive_fg]="#cbc4cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f1b7c4"

# Cpu box outline color
theme[cpu_box]="#948f99"

# Memory/disks box outline color
theme[mem_box]="#948f99"

# Net up/down box outline color
theme[net_box]="#948f99"

# Processes box outline color
theme[proc_box]="#948f99"

# Box divider line and small boxes line color
theme[div_line]="#49454e"

# Temperature graph colors
theme[temp_start]="#cdc2db"
theme[temp_mid]="#d4bbfc"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cdc2db"
theme[cpu_mid]="#d4bbfc"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#cdc2db"
theme[free_mid]=""
theme[free_end]="#4b4358"

# Mem/Disk cached meter
theme[cached_start]="#f1b7c4"
theme[cached_mid]=""
theme[cached_end]="#643b45"

# Mem/Disk available meter
theme[available_start]="#d4bbfc"
theme[available_mid]=""
theme[available_end]="#503c74"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#cdc2db"
theme[download_mid]="#d4bbfc"
theme[download_end]="#f1b7c4"

# Upload graph colors
theme[upload_start]="#cdc2db"
theme[upload_mid]="#d4bbfc"
theme[upload_end]="#f1b7c4"