#  ┳┳┓┏┓┏┳┓┳┳┏┓┏┓┳┓  ┏┓┏┳┓┏┓┏┳┓
#  ┃┃┃┣┫ ┃ ┃┃┃┓┣ ┃┃━━┃┃ ┃ ┃  ┃ 
#  ┛ ┗┛┗ ┻ ┗┛┗┛┗┛┛┗  ┗┻ ┻ ┗┛ ┻ 
#                              



[ColorScheme]
active_colors=#f0dede, #1a1111, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f0dede, #ffffff, #f0dede, #1a1111, #1a1111, #000000, #733335, #ffdad9, #e6bdbc, #ffb3b3, #1a1111, #000000, #1a1111, #f0dede, #e6bdbc
disabled_colors=#f0dede, #1a1111, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f0dede, #ffffff, #f0dede, #1a1111, #1a1111, #000000, #733335, #ffdad9, #e6bdbc, #ffb3b3, #1a1111, #000000, #1a1111, #f0dede, #e6bdbc
inactive_colors=#f0dede, #1a1111, #ffffff, #cacaca, #9f9f9f, #b8b8b8, #f0dede, #ffffff, #f0dede, #1a1111, #1a1111, #000000, #733335, #ffdad9, #e6bdbc, #ffb3b3, #1a1111, #000000, #1a1111, #f0dede, #e6bdbc
